### ISSUE TITLE
Support for timestamp at microsecond precision

### ISSUE THREAD

**Issue by tritas** [marcosschroh/dataclasses-avroschema#101]
Hi, 

Microsecond-precision timestamps are covered in the spec at [Timestamp (microsecond precision)](https://avro.apache.org/docs/current/spec.html#Time+%28microsecond+precision%29). I was looking at the way the library handles them, and it seems they're rounded to millis.

I don't have a PR to propose at the moment, but if there's interest I could write one to handle both use cases. 

**Proposal**

- Millis should probably stay as the default for the ``datetime.time`` type so as not to break existing assumptions/code
- Users could pass some flag in the metadata to signal the field is in micros (opt-in, non-disruptive behaviour)

**Implementation**

Introduces extra logical type mappings ``datetime.time -> fields.TimeMicrosField``  and ``datetime.datetime -> fields.DatetimeMicrosField``. This is turn would require some small changes to the internal API when resolving the field to use, according to the flag.

Let me know if you see a better solution, as I haven't tested the changes yet.

**Comment by marcosschroh** [comment]
Hi @tritas

Thanks for the proposal. What about having this option in the `Meta class`:

```python

class MyAvroModel(AvroModel):
    ...
    my_date_time: datetime.datetime
    my_time: datetime.time

    class Meta:
        datetime_precision = "timestamp-micros"
        time_precision = "time-millis"

#  or per field

class MyAvroModel(AvroModel):
    ...
    my_date_time_1: datetime.datetime
    my_date_time_2: datetime.datetime

    class Meta:
        datetime_precision = {
            "my_date_time_1": "timestamp-millis",
            "my_date_time_2": "timestamp-micros",
        }
```

It it is not specified in the `Meta`, should use the defaults

**Comment by robinderat** [comment]
I would like to see this implemented. 

Right now I'm running into a `OverflowError: date value out of range` when deserialising a timestamp generated in java (apparently in java it is common to use microseconds whereas python expects miliseconds)

**Comment by marcosschroh** [comment]
I will try to solve this asap.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/197

**Comment by Elkasitu** [comment]
Are there any plans to have it be the default for `datetime.datetime` in a major release?

**Comment by marcosschroh** [comment]
Do you mean to have `timestamp-micros` as default logical representation for `datetime.datetime` rather than the current representation `timestamp-millis`? If you meant that then the answer is no.
