### ISSUE TITLE
Avro schema -> dataclass

### ISSUE THREAD

**Issue by eugene-bright** [marcosschroh/dataclasses-avroschema#102]
In my case avro schema is primary and uncontrolled by me.
I'd like to generate dataclass from the avro schema.
Could you share your experience and give me a suggestion on my case?
Also would it be appropriate to add such schema decompliler in your project code if a descent one decompiler was found/written?

**Comment by marcosschroh** [comment]
Hi @eugene-bright 

For now dataclasses-avroschema doesn't have support for a recerse use case. You can take a look this project https://github.com/SRserves85/avro-to-python

**Comment by eugene-bright** [comment]
Thanks for sharing. Mentioned project uses Jinja2. I found nothing better too.
For now I made hackish Jinja2 based transcoder that supports only essential minimum of fields.
Do you have interest in such converter in your project codebase?

**Comment by marcosschroh** [comment]
You're welcome. Yes, would be nice to have the converter. Would you like to work on this?

**Comment by eugene-bright** [comment]
For now I found a cranky way to generate marshmallow-dataclass compatible code. And I'm satisfied with it for now. I'm not sure if I will find time to adapt it for your project.
Names mangling makes my objective (the generation of fully compatible class) almost unfeasible
https://github.com/marcosschroh/dataclasses-avroschema/blob/f17d4b298f35252577a5a2e3976e46720e1b0b54/dataclasses_avroschema/fields.py#L652

**Comment by marcosschroh** [comment]
Ok. Do you think [this](https://github.com/marcosschroh/dataclasses-avroschema/issues/100#issuecomment-859429287) can help you?

**Comment by eugene-bright** [comment]
Yeah, it would help very much.
I'm planning to make a contribution in supporting Int32 (#103) this weekends

**Comment by marcosschroh** [comment]
@eugene-bright 

We have added a new feature: usage of [namespaces](https://marcosschroh.github.io/dataclasses-avroschema/schema_relationships/#avoid-name-collision-in-multiple-relationships) for repetitive schemas and by default the `name` will be `alias or self.type.__name__`. I think this could help you. 

Do you have any progress with this?

**Comment by eugene-bright** [comment]
I made cranky avro -> marshmallow dataclass converter and was happy with it. Currently I'm not work with Avro actively, so if there is no interest for this feature from other participants, please feel free to close the ticket.

**Comment by marcosschroh** [comment]
Ok. Can you create a PR anyway? I can continue your work or maybe other users are interested in continuing it

**Comment by eugene-bright** [comment]
Sorry, I've deleted all local sources once I resigned from the related project.
Anyway I see little point in keeping this ticket open as `marshmallow-dataclass` looks to be more suitable target for code generation.
