### ISSUE TITLE
Specifying the key attribute

### ISSUE THREAD

**Issue by pawelrubin** [marcosschroh/dataclasses-avroschema#111]
**Is your feature request related to a problem? Please describe.**
In **Kafka** it's sometimes necessary to specify which attribute is the `key`, for example, to enable [log compaction](https://kafka.apache.org/documentation/#compaction). 

**Describe the solution you'd like**
It can be achieved via the `Meta` class attibute:

```python
@dataclass
class User(AvroModel):
    _id: str
    name: str

    class Meta:
        key = "_id"
```
or a special type
```python
@dataclass
class User(AvroModel):
    _id: Key[str]
    name: str
```
Then, it can be accessed easily:
```python
user = User.fake()
assert user.key == user._id
```

##
A `key` would have to follow the following rules:
- `key` value has to match some field name
- there can only be one `key` present
- it cannot be optional
- it cannot have a default value (tbh, I'm not sure if this wouldn't be too strict)

##

**Describe alternatives you've considered**
Currently, it can be done via `@property` or by somehow manipulating the metadata.
```python
@dataclass
class User(AvroModel):
    _id: str
    name: str
    
    @property
    def key(self) -> bytes:
        return self._id.encode()
```

**Comment by pawelrubin** [comment]
This seems useful, but it might be too Kafka-specific. However, I imagine there might be more use cases than the **Kafka** one. What do you think?

**Comment by marcosschroh** [comment]
It can be useful, but be aware that any `type` can be encoded (`native, arrays, Dict, AvroModels`, etc). I imagine end users defining custom logic like you mentioned with `@property` or defining any other logic in the model. Maybe as a simple version we could use the `@property` approach:

```python
class AvroModel:
   ...

   @property
   def key(self):
      if self.metadata.key:
          return self.metadata.key.encode()


class MyModel(AvroModel):
    my_key: str
    ...
    
    class Meta:
        key = "my_key"
```

of course this only will work for `str`. For other cases we will need extra logic

**Comment by marcosschroh** [comment]
End users must be responsible of defining the `key` on `kafka`
