### ISSUE TITLE
Support null default for decimal types

### ISSUE THREAD

**Issue by chapm250** [marcosschroh/dataclasses-avroschema#113]
**Is your feature request related to a problem? Please describe.**
It doesn't appear you can set decimal types to have a default of null, if it is possible an example on the decimal documentation would fix this as it's not immediately clear

**Describe the solution you'd like**
A field along the lines of     
```
foo_bar: decimal.Decimal = types.Decimal(
        scale=14, precision=29, default=None
    )
```

Would result in an avro output of 
```
{
	"name": "foo_bar",
	"type": [
		"null",
		{
			"type": "bytes",
			"scale": 14,
			"precision": 29,
			"logicalType": "decimal"
		}
	],
	"default": null
}
```

**Comment by marcosschroh** [comment]
Hi @chapm250 

Thanks for requesting this fix. After finishing https://github.com/marcosschroh/dataclasses-avroschema/issues/92 we are going to work on this fix.

**Comment by bd-cp** [comment]
I have the same need, i.e., a null-able Decimal field. I also am using the pydantic dataclass annotation and ran into a [further validation issue](https://github.com/samuelcolvin/pydantic/issues/1885). I am trying to design a data model/class that both works for Avro and as an OpenAPI implementation.

**Comment by chapm250** [comment]
added support for this in #130
