### ISSUE TITLE
Field.internal_field is None after 0.22

### ISSUE THREAD

**Issue by wicol** [marcosschroh/dataclasses-avroschema#133]
**Describe the bug**
I relied on the Field.internal_field attribute - it is now only set after a Field.generate_items_type(). Not sure if this was intented or not but at least it broke my code. (I'm dynamically adapting a payload to the schema before instantiating).

**To Reproduce**
```python
class Child(AvroModel):
    name: str

class Parent(AvroModel):
    children: typing.List[Child]

> assert Parent.get_fields()[0].internal_field is None
> Parent.get_fields()[0].generate_items_type()
> Parent.get_fields()[0].internal_field
RecordField(name='child', type=<class 'avrotest.Child'>..............
```
**Expected behavior**
I expected Field.internal_field to be populated from the start.

**Comment by marcosschroh** [comment]
Thanks @wicol 

I have released a new version with the fix: https://github.com/marcosschroh/dataclasses-avroschema/pull/134
