### ISSUE TITLE
Any benchmarking data?

### ISSUE THREAD

**Issue by peedrr** [marcosschroh/dataclasses-avroschema#166]
This should really be a discussion item, rather than an issue but I don't see _Discussions_ activated for this project.

I love the concept of this project! I wonder how it stacks up in terms of speed. Have you performed any benchmarks? I would personally be very keen to see how it compares against https://github.com/fastavro/fastavro/

**Comment by marcosschroh** [comment]
Hi @peedrr 

Good to know that you like the project. We do not have any `benchmarking`. This project is using `fastavro` for `serialization` and `deserialization` process.

**Comment by peedrr** [comment]
Fantastic, thanks @marcosschroh. I probably should have dug a little deeper before asking the question 😇

Thanks for the quick response and keep up the good work
