### ISSUE TITLE
Enforcing namespace for user defined types is invalid

### ISSUE THREAD

**Issue by vishalkuo** [marcosschroh/dataclasses-avroschema#174]
**Describe the bug**
Currently, if a type is repeated, its definition _must_ have a namespace defined or a `NameSpaceRequiredException` is raised. However, a namespace is not a requirement in the avro spec. For example, this is a valid avro record:
```json
{
    "type": "record",
    "name": "container",
    "fields": [
        {
            "name": "inner_ref",
            "type": {
                "type": "record",
                "name": "inner_ref",
                "fields": [
                    {
                        "name": "name",
                        "type": "string"
                    }
                ]
            }
        },
        {
            "name": "inner_ref_2",
            "type": "inner_ref"
        },
        {
            "name": "additional_field",
            "type": "long"
        }
    ]
}
```

**To Reproduce**
```python
@dataclass
class InnerClass(AvroModel):
    name: str

    class Meta:
        schema_name = "inner_ref"


@dataclass
class ContainerClass(AvroModel):
    inner_ref: InnerClass
    inner_ref_2: InnerClass
    additional_field: int
```

We should be able to generate a schema without a namespace on `InnerClass`

**Expected behavior**
The above example should not raise a `NameSpaceRequiredException`

**Comment by marcosschroh** [comment]
Hi @vishalkuo,

Thanks for submitting the issue. Even though that the example that you provided without the `namespace` is a valid `avro schema`, I think that the use of `namespaces` is a good practice and they are there for a reason. This library besides the primary goals will encourage good practices to the end users and one of them is the `namespaces` usage. So, for now I will consider this not as an issue.
