### ISSUE TITLE
Pydantic base classes (AvroBaseModel) do not support directly setting doc in Metadata

### ISSUE THREAD

**Issue by leahmcguire** [marcosschroh/dataclasses-avroschema#178]
I love this library :-)

**Describe the bug**
Cannot set the `doc` value for pydantic base classes using the Meta class. Setting the doc explicitly works for the AvroModel but not the AvroBaseModel class. (It can pick up the docstring but I do not want this as the docstring for the class).

**To Reproduce**

```
    class Test(AvroBaseModel):
        value_1: Optional[str] = None
        value_2: str

        class Meta:
            doc: str = "my cool doc string that I do not want to put in the class doc string"
            namespace: str = "stuff.my.name"
```

produces an avro schema of:

`{"type": "record", "name": "Test", "fields": [{"name": "value_1", "type": ["null", "string"], "default": null}, {"name": "value_2", "type": "string"}],  "namespace": "stuff.my.name"}`

**Expected behavior**
should produce

`{"type": "record", "name": "Test", "fields": [{"name": "value_1", "type": ["null", "string"], "default": null}, {"name": "value_2", "type": "string"}],  "namespace": "stuff.my.name", "doc": "my cool doc string that I do not want to put in the class doc string"}`

**Comment by marcosschroh** [comment]
I am glad that you like the library!! 

We don't have this feature. Do you want to send a `PR`?

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/181

Now is is possible to use `Meta.schema_doc` to set the `schema_documentation`
