### ISSUE TITLE
Raise Error for Invalid Dict Field Declaration - Non-String Keys

### ISSUE THREAD

**Issue by Robbie-Palmer** [marcosschroh/dataclasses-avroschema#179]
Avro Maps only support string keys, which is implicit in the schema definition, since the key type cannot be specified e.g.
`{"type" : "map", "values" : "int"}`

An `AvroModel` dataclass can be declared and instantiated with dictionaries with non-string keys according to the typing declaration.
Throwing an error with an invalid `DIct` field key could save some users from bugs / confusing behaviour

```python
from dataclasses import dataclass

from dataclasses_avroschema import AvroModel
from typing import Dict
import json


@dataclass
class DataWithDict(AvroModel):
    num_to_num: Dict[int, int]


print(json.dumps(json.loads(DataWithDict.avro_schema()), indent=4))
# Out:
# {
#     "type": "record",
#     "name": "DataWithDict",
#     "fields": [
#         {
#             "name": "num_to_num",
#             "type": {
#                 "type": "map",
#                 "values": "long",
#                 "name": "num_to_num"
#             }
#         }
#     ],
#     "doc": "DataWithDict(num_to_num: Dict[int, int])"
# }

data = DataWithDict({1: 1, 2: 2})
print(json.dumps(data.asdict(), indent=4))
# Out:
# {
#     "num_to_num": {
#         "1": 1,
#         "2": 2
#     }
# }
```

**Comment by marcosschroh** [comment]
Hi @Robbie-Palmer 

You're right. Do you want to send a PR?

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/180

Now `DataWithDict.avro_schema()` will raise `InvalidMap: Invalid map on field num_to_num. Keys must be string not <class 'int'>`

**Comment by Elkasitu** [comment]
@marcosschroh would you consider a contribution to make this behavior optional? e.g.

```python
from dataclasses import dataclass
from dataclasses_avroschema import AvroModel


@dataclass
class MyModel(AvroModel):
    non_str_key_dict: dict[int, int]
    
    class Meta:
        # can be named allow_non_str_key_map or similar if strict is too generic
        strict = False
```

`fastavro` itself allows serialization of dicts with `int`, `float`, `bool` and `None` keys
