### ISSUE TITLE
Unable to write the sample data with fastavro writer

### ISSUE THREAD

**Issue by noppGithub** [marcosschroh/dataclasses-avroschema#183]
**Describe the bug**
I'm trying to write the AvroModel object to fastavro byte, but failed with the message "argument of type 'User' is not iterable"

**To Reproduce**
`pip install dataclasses-avroschema`

```python
from dataclasses_avroschema import AvroModel
from io import BytesIO
from fastavro import writer, parse_schema

@dataclass
class Address(AvroModel):
    "An Address"
    street: str
    street_number: int


@dataclass
class User(AvroModel):
    "User with multiple Address"
    name: str
    age: int
    addresses: typing.List[Address]


address_data = {
    "street": "test",
    "street_number": 10,
}

# create an Address instance
address = Address(**address_data)

data_user = {
    "name": "john",
    "age": 20,
    "addresses": [address],
}

# create an User instance
user = User(**data_user)

fo = BytesIO()
records = [
    user,
]

writer(fo=fo, schema=User.avro_schema_to_python(), records=records,codec='deflate')
```

**Expected behavior**
Expected to have my user object write into `fo` object using the mentioned writer.

**Comment by marcosschroh** [comment]
Hi @noppGithub 

You have to use a `dictionary` rather than a `class instance` to serialize records using `fastavro`: `records = [user.to_dict()]`

Anyway, `dataclasses-avroschema` provides you a serialization: `user.serialize()` will do the work as well.

**Comment by marcosschroh** [comment]
Close this issue as the error does not exits

**Comment by noppGithub** [comment]
@marcosschroh Sorry for the late reply, you are right about the case Thank you so much <3
