### ISSUE TITLE
Automatic name changes to singular nouns leads to misspelled type names

### ISSUE THREAD

**Issue by marblestation** [marcosschroh/dataclasses-avroschema#190]
**Describe the bug**

Automatic name changes to singular nouns leads to misspelled type names, such as an enum named `marital_status` is renamed to `marital_statu`.

**To Reproduce**

The following code:

```python
import enum
from dataclasses import dataclass
from dataclasses_avroschema import AvroModel

class MaritalStatus(enum.Enum):
    SINGLE = "SINGLE"
    MARRIED = "MARRIED"
    SEPARATED = "SEPARATED"
    WIDOWED = "WIDOWED"

@dataclass
class User(AvroModel):
    "User"
    martial_status: MaritalStatus
```

It generates the following schema:

```json
{
 'type': 'record',
 'name': 'User',
 'fields': [{'name': 'martial_status',
   'type': {'type': 'enum',
    'name': 'martial_statu',
    'symbols': ['SINGLE', 'MARRIED', 'SEPARATED', 'WIDOWED']}}],
 'doc': 'User'
}
```

Where `marital_status` was transformed into `marital_statu`.

The name change happens in:
https://github.com/marcosschroh/dataclasses-avroschema/blob/e7a18486243534038897baa3842d453056de5b1e/dataclasses_avroschema/fields.py#L129-L136

This is inflect not being able to properly treat the composed word:

```python
import inflect
p = inflect.engine()
print(p.singular_noun("marital_status")) # marital_statu
print(p.singular_noun("status")) # status
```

The same problem would happen if English is not the primary language of the code base, for instance, eyeglasses in Spanish:

```
print(p.singular_noun("gafas")) # gafa
```

"Gafas" is converted into "gafa", but in Spanish that word does not exist and eyeglasses is always "gafas" (invariant plural).

**Expected behavior**

The correct behavior is to respect the name `marital_status` and not remove the last `s`. Ideally, the developer should be able to globally enable/disable this automatic behavior since it will get it wrong under certain circumstances.

**Comment by marblestation** [comment]
If anybody else is facing the same problem and do not want to modify `dataclasses-avroschema`, you can create a `inflect.py` file and import it before of importing anything from `dataclasses-avroschema` (or just have it in the python path for your project). The content of the `inflect.py` file:

```python
class Engine:
    def singular_noun(s):
        return s

def engine():
    return Engine
```

**Comment by marcosschroh** [comment]
Hi @marblestation 

Thanks for submitting the issue and for finding an alternative to the users that are facing the same problem. I will work in a PR to fix it.

**Comment by marcosschroh** [comment]
This issue has been resolved by https://github.com/marcosschroh/dataclasses-avroschema/pull/231. Now `Enum's` name follow the [PascalCase](https://github.com/marcosschroh/dataclasses-avroschema/issues/221) convention as it is used in the [avro documentation](https://avro.apache.org/docs/1.10.2/spec.html#Enums) and most importantly they can be reused, meaning that we won't have to always use different names.

For the example given in this issue using the latest version `v0.36.1` the resulting schema is:

```python
import enum
from dataclasses import dataclass
from dataclasses_avroschema import AvroModel

class MaritalStatus(enum.Enum):
    SINGLE = "SINGLE"
    MARRIED = "MARRIED"
    SEPARATED = "SEPARATED"
    WIDOWED = "WIDOWED"

@dataclass
class User(AvroModel):
    "User"
    martial_status: MaritalStatus

User.avro_schema_to_python()

{'type': 'record',
 'name': 'User',
 'fields': [{'name': 'martial_status',
   'type': {'type': 'enum',
    'name': 'MaritalStatus',
    'symbols': ['SINGLE', 'MARRIED', 'SEPARATED', 'WIDOWED']}}],
 'doc': 'User'}
```

For more information you can follow the [documentation](https://marcosschroh.github.io/dataclasses-avroschema/complex_types/#enums)
