### ISSUE TITLE
Implement parse_obj_as

### ISSUE THREAD

**Issue by PetitLepton** [marcosschroh/dataclasses-avroschema#195]
`pydantic` offers a handy standalone function to parse data, `parse_obj_as`, extending `parse_obj` (already implemented in `AvroBaseModel`).

It would be nice to have the same function for `AvroBaseModel`.

For cases like `List[MyModel]`, one can always do something like `[MyModel.parse_obj(datum) for datum in data]` but the syntactic sugar `parse_obj_as(List[MyModel], data)` would allow to be in par with `pydantic`. 

If it makes sense, I could try to help with a PR.

**Comment by marcosschroh** [comment]
Hi @PetitLepton 

I think it makes sense. Looking forward to see the PR.

**Comment by PetitLepton** [comment]
@marcosschroh I feel a bit silly but I realize that, since `AvroBaseModel` inherits from `BaseModel`, one cam straightforwardly use `parse_obj_as`. For example,
```python
In [1]: from dataclasses_avroschema.avrodantic import AvroBaseModel

In [2]: from pydantic import parse_obj_as

In [3]: from typing import List

In [4]: class A(AvroBaseModel):
   ...:     a: int
   ...: 

In [5]: d = [{"a": 1}, {"a": 2}]

In [6]:  l = parse_obj_as(List[A], d)

In [7]: l[0].avro_schema()
Out[7]: '{"type": "record", "name": "A", "fields": [{"name": "a", "type": "long"}]}'

In [8]: l
Out[8]: [A(a=1), A(a=2)]
```
Maybe this is enough? One can import `parse_ob_as` in `avrodantic.py` for cosmetics if necessary.
