### ISSUE TITLE
Defining custom logical types

### ISSUE THREAD

**Issue by Arssham** [marcosschroh/dataclasses-avroschema#209]
Hi! Is there a way to define a custom logical type?

Let's say i want to define such schema
```json
{
  "type": "record",
  "name": "custom.logical.type.schema",
  "doc": "Schema with custom logical type",
  "fields": [
    {
      "name": "event_time",
      "type": {
        "type": "string",
        "logicalType": "iso8601_extended",
        "doc": "Date and time in extended ISO8601 format: 20220223T01:23:45.678+03:00"
      },
      "doc": "Event time"
    }
  ]
}
```

And it would be nice to do something like this
```python
from dataclasses import dataclass, field

from dataclasses_avroschema import AvroModel, CustomType


class ISO8601Extended(CustomType):
    """Date and time in extended ISO8601 format: 20220223T01:23:45.678+03:00"""


@dataclass
class Event(AvroModel):
    """Schema with custom logical type"""
    event_time: ISO8601Extended = field(metadata={"doc": "Event time"})
    
    class Meta:
        schema_name = "custom.logical.type.schema"
```

**Comment by marcosschroh** [comment]
Hi @Arssham 

There is not a way to define custom logical types at the moment but definitely is something that we need.

**Comment by robbertvanwaveren** [comment]
Also I think it would be nice to not dump on unknown custom types but default the base type instead (string in the example above). i.e. if some non-python producer uses a bunch of custom types implemented for their language/convinience then a dataclasses python based consumer should still be able to interpreted the schema/message.
