### ISSUE TITLE
Use Pydantic's `condecimal` instead of the custom Decimal default value

### ISSUE THREAD

**Issue by rgson** [marcosschroh/dataclasses-avroschema#234]
**Is your feature request related to a problem? Please describe.**
This library uses a custom `types.Decimal` as the default value of decimal fields to represent the scale and precision. When generating code from schemas, this creates a model different from what I'd expect (one with a regular decimal default value, or no default value). It also introduces a runtime dependency on this library which is otherwise unnecessary when the code is generated at build time.

**Describe the solution you'd like**
At least when generating Pydantic models, I suggest to use Pydantic's `condecimal` type to represent these constraints instead. `condecimal` has `max_digits` and `decimal_places` which maps rather nicely to `precision` and `scale`. Ideally, this type would be supported in the opposite use-case too (generating schemas from classes).

https://docs.pydantic.dev/usage/types/#arguments-to-condecimal

**Comment by marcosschroh** [comment]
Hi @rgson 

Yes, it makes sense. `Pydantic code generation` must contains only references to `pydantic` fields. I will try to fix it asap.

**Comment by rgson** [comment]
Hi @marcosschroh,

Thanks for the quick implementation!

Unfortunately, I think `condecimal` was used incorrectly, judging from [`test_decimal_field` in the new commit](https://github.com/marcosschroh/dataclasses-avroschema/commit/b10c8879a88aa3e44047b052ab7c5b67d83452d1#diff-5c592da0aff54eb288c6a7c8e60def95ef16ca817b94ad14b6ff6ede385b5e7b). I think my wording in the top post may have contributed to that, sorry!

`condecimal` is meant to be used as a type hint, not as the default value. Examples: https://docs.pydantic.dev/usage/types/#constrained-types

To demonstrate the problem:
```py
import decimal
import pydantic


class DemoA(pydantic.BaseModel):
    foo: decimal.Decimal = pydantic.condecimal(max_digits=10, decimal_places=3)
 
a = DemoA(foo="1.234")
# DemoA()
a.foo
# <class '__main__.ConstrainedDecimalValue'>

a = DemoA(foo="1.23456789")
# DemoA()
a.foo
# <class '__main__.ConstrainedDecimalValue'>


class DemoB(pydantic.BaseModel):
    foo: pydantic.condecimal(max_digits=10, decimal_places=3)
 
b = DemoB(foo="1.234")
# DemoB(foo=Decimal('1.234'))
b.foo
# Decimal('1.234')

b = DemoB(foo="1.23456789")
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
# pydantic.error_wrappers.ValidationError: 1 validation error for DemoB
# foo
#   ensure that there are no more than 3 decimal places (type=value_error.decimal.max_places; decimal_places=3)
```

**Comment by marcosschroh** [comment]
Hi, 

When I have some time I will fix it. Thanks for let me know.

**Comment by marcosschroh** [comment]
@rgson I have updated the project, now the `condecimal` is used to generate the [type](https://marcosschroh.github.io/dataclasses-avroschema/model_generator/#render-pydantic-models)

**Comment by rgson** [comment]
> @rgson I have updated the project, now the `condecimal` is used to generate the [type](https://marcosschroh.github.io/dataclasses-avroschema/model_generator/#render-pydantic-models)

I've now upgrade to a newer version and tried it out. LGTM. Thanks!
