### ISSUE TITLE
NameSpaceRequiredException on enum when parsing json data

### ISSUE THREAD

**Issue by florissmit10** [marcosschroh/dataclasses-avroschema#240]
**Describe the bug**
When an Enum is used in multiple places it gives a NameSpaceRequiredException when trying to parse an object. It looks like a bug, but if im using the library in a wrong way please let me know :)

**To Reproduce**
```python
class C(enum.Enum):
    ENUM_VALUE = "C_ENUM"


@dataclass
class B(AvroModel):
    b: str
    c: C


@dataclass
class A(AvroModel):
    a: str
    b: B
    c: C


def test_nested():
    input_json = """
        {
        "a": "a",
        "b": { "b": "b", "c": "C_ENUM"}, 
        "c": "C_ENUM"}"""

    obj = A.parse_obj(json.loads(input_json))
    assert obj.validate()

    assert type(obj) is A
    assert obj.a == "a"
    assert type(obj.b) is B
    assert obj.b.b == "b"
    assert type(obj.b.c) is C
```

**Expected behavior**
I expect the above test to pass

**Comment by marcosschroh** [comment]
Hi @florissmit10 

When you use `enums` multiple times in the same schema you have to define the `namaspace`. It is a good practice to do it. Here you can find the documentation https://marcosschroh.github.io/dataclasses-avroschema/complex_types/#repeated-enums
