### ISSUE TITLE
NameSpaceRequiredException when reusing child class

### ISSUE THREAD

**Issue by mhils** [marcosschroh/dataclasses-avroschema#246]
Hi there! First off, thank you for the fantastic library. 🍰 

I'm running into the following issue in a migration to dataclasess-avroschema:

```python
from dataclasses_avroschema.avrodantic import AvroBaseModel


class ChildA(AvroBaseModel):
    id: int


class ChildB(AvroBaseModel):
    id: int


class Parent(AvroBaseModel):
    x: ChildA | ChildB
    y: ChildA | ChildB

    class Meta:
        namespace = "com.example"


d = Parent(x=ChildA(id=42), y=ChildB(id=43))
print(d.serialize(serialization_type="avro-json"))
```
```
  File "C:\Python3.11\Lib\site-packages\dataclasses_avroschema\fields.py", line 773, in get_avro_type
    raise NameSpaceRequiredException(field_type=self.type, field_name=self.name)
dataclasses_avroschema.exceptions.NameSpaceRequiredException: Required namespace in Meta for type <class '__main__.ChildA'>. The field y is using an exiting type
```

Removing `y` fixes the issue and correctly produces:
```json
{"x": {"com.example.ChildA": {"id": 42}}}
```

The problem seems to be that `exist_type` turns `True`, but I don't understand enough of the codebase to know what the correct  fix is. 😃

**Comment by marcosschroh** [comment]
You're welcome. The error `dataclasses_avroschema.exceptions.NameSpaceRequiredException: Required namespace in Meta for type <class '__main__.ChildA'>. The field y is using an exiting type` says that you have to define a `namespace` for `type <class '__main__.ChildA'>`. The same should be done for `type <class '__main__.ChildB'>:

```python
from dataclasses_avroschema.avrodantic import AvroBaseModel


class ChildA(AvroBaseModel):
    id: int

    class Meta:
        namespace = "com.example"

class ChildB(AvroBaseModel):
    id: int

    class Meta:
        namespace = "com.example"

class Parent(AvroBaseModel):
    x: ChildA | ChildB
    y: ChildA | ChildB

    
d = Parent(x=ChildA(id=42), y=ChildB(id=43))
print(d.serialize(serialization_type="avro-json"))

# >>> b'{"x": {"com.example.ChildA": {"id": 42}}, "y": {"com.example.ChildA": {"id": 43}}}'
```

**Comment by marcosschroh** [comment]
You're welcome. The problem here is that when there are "schema relationships" and a `type` is used more than once (like in your example) the [namespace is required](https://marcosschroh.github.io/dataclasses-avroschema/schema_relationships/#avoid-name-collision-in-multiple-relationships). I see this as a good practice to always include the `namespace`  but in reality it is not required (the `avsc` schema generated with `avro-tools` is also correct if it does not include  the `namespaces`). Perhaps we should remove this [hard restriction ](https://github.com/marcosschroh/dataclasses-avroschema/blob/master/dataclasses_avroschema/fields.py#L773)

**Comment by mhils** [comment]
I see that the namespace is required at the moment, but I don't think I don't exactly understand why that's the case? It seems like the existing type could just be reused then? If I apply the patch below, things just work for me (except for a test that basically matches the problem here and expects an error).

<details><summary>patch.diff</summary>
<pre><code>
diff --git a/dataclasses_avroschema/fields.py b/dataclasses_avroschema/fields.py
index 10cb8a1..6a4a472 100644
--- a/dataclasses_avroschema/fields.py
+++ b/dataclasses_avroschema/fields.py
@@ -748,8 +748,9 @@ class RecordField(BaseField):
             record_type["name"] = name
         else:
             if metadata.namespace is None:
-                raise NameSpaceRequiredException(field_type=self.type, field_name=self.name)
-            record_type = f"{metadata.namespace}.{name}"
+                record_type = name
+            else:
+                record_type = f"{metadata.namespace}.{name}"
         if self.default is None:
             return [field_utils.NULL, record_type]
</code></pre></details>

Here's a full repro that matches more closely what I'm doing:

```python
from pathlib import Path
from subprocess import run
import json

if False:
    # generate avsc
    Path("example.avdl").write_text("""
    @namespace("com.example")
    protocol MyProtocol {
      record Child {
        int id;
      }
    
      record Parent {
        union { null, Child } x;
        union { null, Child } y;
      }
    }
    """)
    run(["java", "-jar", "avro-tools-1.11.1.jar", "idl2schemata", "./example.avdl"], check=True)
else:
    # same as above, just hardcoded.
    Path("Parent.avsc").write_text("""
    {
      "type" : "record",
      "name" : "Parent",
      "namespace" : "com.example",
      "fields" : [ {
        "name" : "x",
        "type" : [ "null", {
          "type" : "record",
          "name" : "Child",
          "fields" : [ {
            "name" : "id",
            "type" : "int"
          } ]
        } ]
      }, {
        "name" : "y",
        "type" : [ "null", "Child" ]
      } ]
    }
    """)


# Convert avsc to Python
from dataclasses_avroschema import ModelGenerator

model_generator = ModelGenerator()
schema = json.loads(Path("Parent.avsc").read_text())
result = model_generator.render(schema=schema)
Path("generated.py").write_text(result)


# Try to serialize generated model
from generated import Parent, Child

d = Parent(
    x=Child(id=42),
    y=Child(id=43),
)
print(d.serialize(serialization_type="avro-json"))  # NameSpaceRequiredException
```

**Comment by marcosschroh** [comment]
Yes, the existing type can be reused so you don’t have to repeat the whole schema again, instead use the `field.name`. We should applied the patch, probably after merging your PR
