### ISSUE TITLE
Support for typing.Optional

### ISSUE THREAD

**Issue by yankees714** [marcosschroh/dataclasses-avroschema#25]
Hello, and thanks for the awesome project!

I'm looking to generate schemas with nullable fields from dataclass fields of type `typing.Optional`. It looks like a similar result can be achieved using a default value of `= None`, but (1) there are cases where a default might not be desired, and (2) this doesn't play nicely with type checkers like mypy without using `typing.Optional`.

I have a potential patch here (which works for my use case): https://github.com/marcosschroh/dataclasses-avroschema/compare/marcosschroh:c730da6...yankees714:a28d2ac. If this looks like something you'd be interested in adding to the project, I'd be happy to open a PR!

**Comment by marcosschroh** [comment]
Hi @yankees714 ,

Thanks!! Yes, we can add it to the library. I think [here](https://github.com/marcosschroh/dataclasses-avroschema/compare/marcosschroh:c730da6...yankees714:a28d2ac#diff-f59928c2c230ebccf0b665768ce86a2aR171) should be `NoneField` instead of `NoneTypeField`

**Comment by yankees714** [comment]
Sounds good! Opened https://github.com/marcosschroh/dataclasses-avroschema/pull/26.

**Comment by marcosschroh** [comment]
close by https://github.com/marcosschroh/dataclasses-avroschema/pull/26
