### ISSUE TITLE
AvroBaseModel.avro_schema() returns different schemas

### ISSUE THREAD

**Issue by vegraux** [marcosschroh/dataclasses-avroschema#254]
**Describe the bug**
I got a `AvroBaseModel` called `MyModel` that has another `AvroBaseModel` called `NestedModel` as a field. I get different schemas when I call `MyModel.avro_schema()` twice. The field of the second schema corresponding to NestedModel  simply refers to itself as type: `{'name': 'nested_model', 'type': 'NestedModel'}`

**To Reproduce**
I am using `dataclasses-avroschema==0.37.4` and Python 3.10.6

Code to reproduce the problem:
```python
import json

from dataclasses_avroschema.avrodantic import AvroBaseModel


class NestedModel(AvroBaseModel):
    nesten_hello: str


class MyModel(AvroBaseModel):
    hello: str
    nested_model: NestedModel


schema1 = json.loads(MyModel.avro_schema())

schema2 = json.loads(MyModel.avro_schema())


assert schema1 == schema2, "not equal schemas"
```

**Expected behavior**
`MyModel.avro_schema()` should be idempotent, and return the same schema every time

**Comment by vegraux** [comment]
Quick service, thanks!

**Comment by marcosschroh** [comment]
You're welcom!
