### ISSUE TITLE
Issues creating Field Level Doc attributes using AvroBaseModel

### ISSUE THREAD

**Issue by tanzim-bgl** [marcosschroh/dataclasses-avroschema#263]
**Describe the bug**

Using the AvroModel base class allows me to create a 'field' level attribute:

```python
@dataclass
class Event(AvroModel):
    metadata: str = field(metadata={"doc": "bar"})

print(Event.avro_schema())
```

```json
{"type": "record", "name": "Event", "fields": [{"doc": "bar", "name": "metadata", "type": "string"}], "doc": "Event(metadata: str)"}
```

But when I use AvroBaseModel and pydantic.Field then it does not render, the source code shows the classes with attributes 'doc' should be picked up and it does so for AvroModel...

Also I have tried using dataclasses.field which has led to issues because of a 'mapping proxy' error, where the deep copy does not work. I used the pydantic fields instead. 

I am aware that there docs captured from the doc string in a Pydantic class, but I would like to know how to apply at a field level eg.

```python
class Event(AvroBaseModel):
    metadata: str = Field(metadata={"doc": "bar"})

print(Event.avro_schema())
```

```json
{"type": "record", "name": "Event", "fields": [{"name": "metadata", "type": "string"}]}
```

Also using regular dataclasses field, is not compatible

I would love to leverage the pydantic data validation as it looks the cleanest and is super helpful with sparse data and exceptions.

**Comment by marcosschroh** [comment]
Hi @tanzim-bgl 

I will try to fix it asap! Thanks for finding this bug.
