### ISSUE TITLE
License discrepancy

### ISSUE THREAD

**Issue by yankees714** [marcosschroh/dataclasses-avroschema#28]
I noticed that this project uses the  MIT license, but the [`setup.py`](https://github.com/marcosschroh/dataclasses-avroschema/blob/bd853db6248fff35f797fe63ba5b2a1c3a08812b/setup.py#L26) specifies the license as GPLv3. Based on the commit history, seems like MIT is the intended license, and I think the `setup.py` may just need updating?

**Comment by marcosschroh** [comment]
Hi @yankees714 ,

Yes, `MIT` is the intended license. You're welcome to send a `PR`
