### ISSUE TITLE
Bad interactions with __future__.annotations

### ISSUE THREAD

**Issue by jmtroth0** [marcosschroh/dataclasses-avroschema#295]
**Describe the bug**
When using `from __future__ import annotations` to allow better type hints, this package seems not to appropriately recognize types from dataclasses. This seems to impact everything from `str`s and `int`s to other classes that inherit from `AvroModel`s.

**To Reproduce**
Here is a minimal example

```
from __future__ import annotations

from dataclasses import dataclass

from dataclasses_avroschema.schema_generator import AvroModel

@dataclass
class Avro(AvroModel):
    id: int
    name: str

Avro.avro_schema()
```
This throws an exception:

`ValueError: Type int is unknown. Please check the valid types at https://marcosschroh.github.io/dataclasses-avroschema/fields_specification/#avro-field-and-python-types-summary`

**Expected behavior**
`int`s, `str`s, and any other types should be able to schematize correctly even when importing future annotations.

**Comment by marcosschroh** [comment]
Hi @jmtroth0 

This is a duplicated [issue](https://github.com/marcosschroh/dataclasses-avroschema/issues/96) and related but a python bug https://github.com/python/cpython/issues/83623

This is the last recommendation:

> Do not use from __future__ import annotations when you need actual type object.
> This option won't be default. So no plan to fix it.
> 
> PEP 649 will be accepted, but you can not use it for now.
