### ISSUE TITLE
Fields of type fixed

### ISSUE THREAD

**Issue by m0baxter** [marcosschroh/dataclasses-avroschema#31]
I am trying to create a field of type `fixed`, even something simple like this
```
{
   "type": "record",
   "name": "record_name",
   "fields": [
      {
         "name": "field_name",
         "type": {
            "type": "fixed",
            "size": "16"
         }
      }
   ]
}
```
I can't find any documentation for this and `grep`-ing the repository directory doesn't find anything relevant.

**Comment by marcosschroh** [comment]
Hi,

Yes, we still need to add support for `fixed` type. I will try to add it in coming weeks. Anyway, be my guest if you want to send a `PR`

**Comment by marcosschroh** [comment]
@m0baxter I have added support for fixed types: https://marcosschroh.github.io/dataclasses-avroschema/complex_types/

closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/32
