### ISSUE TITLE
Pydantic excluded fields are being exported to schema and fail serialization

### ISSUE THREAD

**Issue by michal-rogala** [marcosschroh/dataclasses-avroschema#314]
Hello!

When using pydantic (AvroBaseModel) - if a field is marked as excluded, it's still being exported to schema and serialization raises an error. Pydantic internal fields (beginning with underscore) are being ignored but those marked as excluded are not.

**Current behavior:**

```
from dataclasses_avroschema.avrodantic import AvroBaseModel
from pydantic import Field

class Message(AvroBaseModel):
    internal_field: str = Field(exclude=True)
    public_field: str

print(Message.avro_schema())
```

this results in schema:
`{"type": "record", "name": "Message", "fields": [{"name": "internal_field", "type": "string"}, {"name": "public_field", "type": "string"}]}`

Object serialization:

```
m = Message(internal_field="internal", public_field="public")
print(m.serialize(serialization_type="avro-json"))
```

raises an error:
```
fastavro/_write_py.py", line 252, in write_record
    raise ValueError(f"no value and no default for {name}")
ValueError: no value and no default for internal_field
```
Which of course make sense as this value is not provided by pydantic - because it's excluded.

**Expected behavior**
Excluded message is not reflected in schema and serialization.

**Comment by marcosschroh** [comment]
Hi @michal-rogala 

Thanks for reporting the bug. I will try to solve it asap

**Comment by michal-rogala** [comment]
perfect, thank you :)

**Comment by michal-rogala** [comment]
@marcosschroh hi! I just found out that similar issue happens with classmethods defined for a pydantic class:

`(type <class 'method'>) do not match ['null', 'string'] on field type`

**Comment by marcosschroh** [comment]
I have released a new version with the fix. Here is the [documentation](https://marcosschroh.github.io/dataclasses-avroschema/pydantic/#excluding-fields)

**Comment by michal-rogala** [comment]
thank you! :)
