### ISSUE TITLE
faust + AvroBaseModel

### ISSUE THREAD

**Issue by hgalytoby** [marcosschroh/dataclasses-avroschema#320]
I know it is possible to write
https://marcosschroh.github.io/dataclasses-avroschema/records/

I want to have the function of validating data, so I want to use AvroBaseModel.

But there will be `object has no field "__evaluated_fields__"` problem.

Is there a way to solve? Or is there any other way to validate data when using faust + AvroModel?

**Comment by marcosschroh** [comment]
Hi @hgalytoby,

It is not possible, here is the explanation: https://github.com/marcosschroh/dataclasses-avroschema/issues/207#issuecomment-1288942997

If you want to use only `faust`, you can use the `validate` method or set `validation=True`: https://faust-streaming.github.io/faust/userguide/models.html#validation

**Comment by marcosschroh** [comment]
I have added some [documentation](https://marcosschroh.github.io/dataclasses-avroschema/faust_records/#data-validation) about how to validate data with faust.
