### ISSUE TITLE
Data class / pydantic model generation fails if field contains default value

### ISSUE THREAD

**Issue by nukemichaels** [marcosschroh/dataclasses-avroschema#348]
**Describe the bug**
`model_generator::render` method throws `unhashable type: 'dict'` if default value is set for a field with defined `java-class` property. Same behavior observed for both data class and Pydantic model generators.

**To Reproduce**

In this example
```python
from dataclasses_avroschema import ModelGenerator, BaseClassEnum

model_generator = ModelGenerator(base_class=BaseClassEnum.PYDANTIC_MODEL.value)
schema = {
  "type": "record",
  "name": "User",
  "fields": [
    {
      "name": "fullName",
      "type": {
        "type": "string",
        "java-class": "java.lang.String"
      },
      "default": "John Doe"
    }
  ]
}
result = model_generator.render(schema=schema)
with open("model.py", mode="+w") as f:
    f.write(result)
```
execution fails on line `result = model_generator.render(schema=schema)` with error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-102-c4e592638c6d>](https://localhost:8080/#) in <cell line: 18>()
     16   ]
     17 }
---> 18 result = model_generator.render(schema=schema)
     19 with open("model.py", mode="+w") as f:
     20     f.write(result)

6 frames
[/usr/local/lib/python3.10/dist-packages/dataclasses_avroschema/model_generator/generator.py](https://localhost:8080/#) in get_field_default(self, field_type, default, name)
    455         elif isinstance(field_type, list):
    456             return self.get_field_default(field_type=field_type[0], default=default, name=name)
--> 457         elif field_type in avro_to_python_utils.LOGICAL_TYPES_TO_PYTHON:
    458             func = avro_to_python_utils.LOGICAL_TYPES_TO_PYTHON[field_type]
    459             python_type = func(default)

TypeError: unhashable type: 'dict'
```

Generator works fine if I either remove default value field or change type definition to:
```json
    {
      "name": "fullName",
      "type": "string",
      "default": "John Doe"
    }
```

**Expected behavior**
Since Avro schema is valid, generator should create valid Pydantic model:
```python
from pydantic import BaseModel

class User(BaseModel):
    fullName: str = "John Doe"
```

**Comment by marcosschroh** [comment]
Hi @nukemichaels 

What you are trying to do it not possible. `java-class` is not a valid property in avro schemas [specification](https://avro.apache.org/docs/1.11.1/specification/). Can you explain why are you using that property?

**Comment by robbertvanwaveren** [comment]
Actually, it is quite common for generators to add this and other fields to the schema they produce specifically for client/language generation support. The spec actually does allow for it: "Attributes not defined in this document are permitted as metadata"

**Comment by marcosschroh** [comment]
Ah now I understand. I do not see really often fields definitions as `defined type names`. Definitely is a bug and actually the code generated should include the metadata as well: 

```python
from pydantic import BaseModel, Field

class User(BaseModel):
    fullName: str = Field(default="John Doe", metadata={"java-class": "java.lang.String"})
```

I will try to fix asap.

**Comment by marcosschroh** [comment]
@robbertvanwaveren @nukemichaels now this is fix in the latest version
