### ISSUE TITLE
mypy throws an error when using condecimal type

### ISSUE THREAD

**Issue by michal-rogala** [marcosschroh/dataclasses-avroschema#350]
When using condecimal as type alias, mypy throws an error:

```
error: Variable "xyz.types.Decimal" is not valid as a type  [valid-type]
xyz/schema.py:15: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```

In our schema we use a custom Decimal definition declared as:

```
from dataclasses_avroschema import types

_decimal = types.condecimal(max_digits=20, decimal_places=6)
Decimal = _decimal
```

We tried declaring `Decimal` and `_decimal` as TypeAlias but the mypy error was that `_decimal` can not be an expression.

cc: @ddevlin

**Comment by marcosschroh** [comment]
Hi @michal-rogala 

When I use `types.condecimal(...)` in an `AvroModel` I have the following `mypy` error:

```
Invalid type comment or annotation  [valid-type]mypy(error)
Suggestion: use types.condecimal[...] instead of types.condecimal(...)mypy(note)
(module) types
```

Mypy version:

```
mypy==1.3.0
mypy-extensions==1.0.
```
What you can do is:

1. Use `type: ignore`
2. Use `Annotated`

```python
from typing import Annotated
import decimal

from dataclasses_avroschema import AvroModel, types, DecimalFieldInfo


class ExampleAvroModel):
    decimal_with_default: Annotated[decimal.Decimal, DecimalFieldInfo(max_digits=5, decimal_places=6)] = decimal.Decimal("3.14159")
```

The `condecimal` function is doing exactly the same thing that I show with the `Annotated` example but somehow `mypy` can not interpreted correctly.

**Comment by ddevlin** [comment]
> ```
> _decimal = types.condecimal(max_digits=20, decimal_places=6)
> CustomDecimal = _decimal
> ```
No solution unfortunately, but more context: this is different to the behaviour in `pyright`:
- in `pyright` the type of `_decimal` is seen as a `Type[Decimal]` assigned to a variable 
- assigning it to `CustomDecimal` is seen as a type alias, and can be used to type AvroModel fields without complaints from the type checker.

<img width="473" alt="Screenshot 2023-06-28 at 15 20 20" src="https://github.com/marcosschroh/dataclasses-avroschema/assets/912471/0048b039-3690-4100-9f3a-918017d071b7">

<img width="399" alt="Screenshot 2023-06-28 at 15 24 35" src="https://github.com/marcosschroh/dataclasses-avroschema/assets/912471/aa2bf853-0c62-40c7-9a0c-a7db5e095989">

<img width="989" alt="Screenshot 2023-06-28 at 15 27 21" src="https://github.com/marcosschroh/dataclasses-avroschema/assets/912471/66f24dca-d7ba-4574-b8d7-fb4db6ee2c77">

**Comment by marcosschroh** [comment]
I think I found a workaround for this issue using  `typing.TYPE_CHECKING` as `mypy` does not evaluate code: _typing.TYPE_CHECKING is A special constant that is assumed to be True by 3rd party static type checkers. It is False at runtime._

 In this way, `mypy` will not complaint because we specify the static definition and we use the proper one on runtime.

```python
import decimal
import typing
from dataclasses import dataclass

from dataclasses_avroschema import AvroModel, types

if typing.TYPE_CHECKING:
    MyDecimal = decimal.Decimal
else:
    MyDecimal = types.condecimal(max_digits=20, decimal_places=6)


@dataclass
class A(AvroModel):
    my_decimal: MyDecimal
```

In this case I think it works nicely as the value returned by `condecimal` is a `decimal.Decimal` 😁

**Comment by michal-rogala** [comment]
it's a nice solution, thanks! :)
