### ISSUE TITLE
Unable to do avro_schema_to_python in the latest version

### ISSUE THREAD

**Issue by noppGithub** [marcosschroh/dataclasses-avroschema#381]
**Describe the bug**
`pip install dataclasses-avroschema[pydantic]`
or 
```bash
pip install 
dataclasses-avroschema==0.45.0
pydantic==2.0
```

```python
from typing import Optional
from dataclasses_avroschema.avrodantic import AvroBaseModel

class Order(AvroBaseModel):
    id: Optional[str]
    admin_graphql_api_id: Optional[str]
    app_id: Optional[str]

if __name__ == "__main__":
    x = Order.avro_schema_to_python()
    print(x)
```
This code working fine with `dataclasses-avroschema==0.36.1`, but `dataclasses-avroschema==0.45.0` has error below

0.36.1 works fine
```json
{'type': 'record', 'name': 'Order', 'fields': [{'name': 'id', 'type': ['null', 'string'], 'default': None}, {'name': 'admin_graphql_api_id', 'type': ['null', 'string'], 'default': None}, {'name': 'app_id', 'type': ['null', 'string'], 'default': None}]}
```
0.45.0 not working
```json
Field name "schema_def" shadows an attribute in parent "AvroModel"; you might want to use a different field name with "alias='schema_def'".
```

Expected that the version 0.45.0 can do the same.

**Comment by dabdada** [comment]
When having something in the avro model that is not json serializable it also fails on the json.dumps call.

e.g. we have event_time in a model and when the render_schema function is called it results in ` 'event_time': datetime.datetime(2023, 8, 4, 14, 17, 37, 69902),` but should probably be something like `'event_time': '2023-08-04T14:17:37'`

**Comment by marcosschroh** [comment]
Hi all!

Currently we do not support `pydantic v2` but coming weeks I will try to migrate or add  support for it.

**Comment by marcosschroh** [comment]
Closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/455
