### ISSUE TITLE
Make `faker` an optional dependency.

### ISSUE THREAD

**Issue by aalekhpatel07** [marcosschroh/dataclasses-avroschema#390]
Hey there!

Along the lines of #292, I was wondering if there is any interest in making `faker` an optional dependency. 

One of my current project setups require me to pin `faker<=2.0.4` as a dev dependency, and this conflicts with it being a hard run-time dep for `dataclasses_avroschema`. I think it'd be neat to use this library so please advise on the best way to proceed. If you can't find the time, thats fine too, as I can try to contribute.

**Comment by marcosschroh** [comment]
Hi, yes we can do it.

**Comment by aalekhpatel07** [comment]
Thanks for the merge. For posterity, this is introduced in [Release 0.47.0](https://github.com/marcosschroh/dataclasses-avroschema/releases/tag/0.47.0) :rocket: :tada:
