### ISSUE TITLE
`AvroBaseModel.avro_schema` error for arbitrary types

### ISSUE THREAD

**Issue by OffByOnee** [marcosschroh/dataclasses-avroschema#392]
**Describe the bug**
The `AvroBaseModel.avro_schema` method doesn't appear to support arbitrary types that are compatible with the `pydantic.BaseModel.schema` method.

**To Reproduce**
```python3
from dataclasses_avroschema.avrodantic import AvroBaseModel


class MyClass:
    def __init__(self) -> None:
        self.my_field = 'Hello World'

    @classmethod
    def __modify_schema__(cls, field_schema: dict) -> None:
        field_schema.update(title='MyClass', type='string')

    def __str__(self) -> str:
        return self.my_field

    def __repr__(self) -> str:
        return self.my_field

class ModelWithArbitraryType(AvroBaseModel):
    class Config:
        arbitrary_types_allowed = True
        json_encoders= {MyClass: str}

    field: MyClass


model = ModelWithArbitraryType(field=MyClass())
print(model.schema())
print(model.avro_schema())
```

outputs:
```
{'title': 'ModelWithArbitraryType', 'type': 'object', 'properties': {'field': {'title': 'MyClass', 'type': 'string'}}, 'required': ['field']}

ValueError: Type <class '__main__.MyClass'> is unknown. Please check the valid types at https://marcosschroh.github.io/dataclasses-avroschema/fields_specification/#avro-field-and-python-types-summary
```

**Expected behavior**
I expected `avro_schema` to support arbitrary types when `Config` has `arbitrary_types_allowed = True` and the user class defines `__modify_schema__` method.

**Comment by marcosschroh** [comment]
It is not supported by the fact that it does not make any sense to have an `arbitrary_type` which won't be included in the `avro schema`. 

Could you answer the following questions?

1. What would be the idea of having a type that is not included in the final schema? 
2. How would you manage the situation to deserialze an event that does not contain the `arbitrary_type`?

**Comment by OffByOnee** [comment]
@marcosschroh thanks for getting back to me so quickly.

I was thinking:
1. The type would be included in the final schema
2. The event would be required to contain the arbitrary type

An example of this use case is a bson ObjectId. I would serialize the ID as a string in accordance with the `__modify_schema__` method, and fastavro serialization would raise an exception if I provided a data type that doesn't match the schema.

**Comment by marcosschroh** [comment]
You're welcome @OffByOnee 

But if the `type` (arbitrary type) should be in the schema and the event should contain the `arbitrary type` then it means that it should not be an `arbitrary type` because it must be validated.

According to the `pydantic` documentation: 
> Nothing in the instance of the arbitrary type is checked

which means that the instance  `arbitrary_type` could contain anything and then it might not match the schema.

I think that:

1. If the `arbitrary_type` must be in the schema then it should not be an `arbitrary_type`.
2. I recognize that there is not a way to exclude fields that should be in the class but not in the schema. In other words: It there is an `arbitrary_type` then it should not be included in the schema

Does it makes sense?

**Comment by OffByOnee** [comment]
I think so. So, if I'm following you correctly, you're saying that we should just change the arbitrary class to inherit from `AvroBaseModel` if we want it to show up in the schema and serialized data?

I'm on-board with that - the only challenge is when my model has types that are from 3rd party libraries (since I can't modify them), which I think it why `pydantic` supports [generic-classes-as-types](https://docs.pydantic.dev/1.10/usage/types/#generic-classes-as-types). As I'm reading that section I realize that my use of "arbitrary types" in this thread was incorrect, so I do apologize. I guess what I really have in mind is "Generic Classes" that have well-defined validation and a [customized schema](https://docs.pydantic.dev/1.10/usage/schema/#modifying-schema-in-custom-fields) that matches the [json encoding logic](https://docs.pydantic.dev/1.10/usage/exporting_models/#json_encoders).

Let me a take a step back and explain big picture what I'm hoping to accomplish. I have a project where I'm using `pydantic` to model database tables. A situation recently popped up requiring me to serialize those models into Avro format. `pydantic` does an awesome job at generating JSON schemas, but sadly doesn't support generating Avro schemas. So I was poking around for a library that could help with that and yours here looked like it could be a great fit. I tried swapping the base class of my models from `BaseModel` to `AvroBaseModel`, and then ran into the arbitrary type issue when generating the Avro schemas.

Here's a more representative example of what I'm attempting (with use of arbitrary types omitted in favor of Generic Classes):
```python
import typing
from io import BytesIO
from json import dumps, loads

from bson import ObjectId as BsonObjectId  # 3rd party class that I can't modify
from bson.errors import InvalidId
from dataclasses_avroschema.avrodantic import AvroBaseModel
from fastavro import writer


# The imported ObjectId isn't a pydantic model, so I'm creating a "Generic Class"
# that customizes the schema and validation for this type
class ObjectId(
    BsonObjectId,
):
    """
    Extends bson's ObjectId, so that we can generate JSON schemas for
    data models
    """
    @classmethod
    def __get_validators__(
        cls,
    ) -> typing.Generator[typing.Callable[..., typing.Self], typing.Any, None]:
        yield cls.validate

    # This method tells pydantic how to convert a value into an ObjectId
    @classmethod
    def validate(
        cls,
        value: typing.Any,
    ) -> typing.Self:
        try:
            return cls(value)
        except InvalidId:
            raise ValueError(f'{value} is not a valid ObjectId')

    # This method tells pydantic how to generate a JSON schema for this class
    @classmethod
    def __modify_schema__(
        cls,
        field_schema: dict,
    ) -> None:
        field_schema.update(
            title='Id',
            type='string',
        )


# This an example that has a field of "Generic Class" type
class MyModel(AvroBaseModel):
    id: ObjectId

    class Config:
        json_encoders = {ObjectId: str}  # ObjectId can be safely converted to a string


model = MyModel(id=ObjectId())

# .json converts ObjectId to its string representation because of the json_encoder that we
# specified, and loads converts it back to a dictionary that can be serialized into Avro
serializable_model = loads(model.json())

# This outputs a string because of the above conversion
print(serializable_model['id'])

# Now attempt to serialize the data into Avro
data_to_serialize = [serializable_model]
serialized_data = BytesIO()

writer(
    serialized_data,
    model.avro_schema_to_python(),  # <--- This is the part I'm currently having trouble with due to ObjectId not being a supported type
    data_to_serialize,
)
```

That line at the bottom is the one that I'm having trouble with: `model.avro_schema_to_python()`. It raises
```python
ValueError: Type <class '__main__.ObjectId'> is unknown. Please check the valid types at https://marcosschroh.github.io/dataclasses-avroschema/fields_specification/#avro-field-and-python-types-summary
```
Now if I generate a JSON schema through `pydantic` I get the following output:
```json
{
  "title": "MyModel",
  "type": "object",
  "properties": {
    "id": {
      "title": "Id",
      "type": "string"
    }
  },
  "required": [
    "id"
  ]
}
```
where the ObjectId is represented as a string, which is great - that's what I wanted. I was hoping that a call to `model.avro_schema_to_python()` would generate the same thing, but in Avro. Do you think this is something that can be accomplished? I'd be happy to implement the solution myself and submit a PR, but first I wanted to see if this was even in the realm of possibility and if you'd be on-board with it.

**Comment by marcosschroh** [comment]
Hi @OffByOnee,

> if I'm following you correctly, you're saying that we should just change the arbitrary class to inherit from AvroBaseModel if we want it to show up in the schema and serialized data?

Yes!!

> Do you think this is something that can be accomplished? If it isn't already supported (not sure if my configuration for this use-case is correct) and you're on-board with adding support then I'd be happy to implement a solution and submit a PR.

It is not supported. A PR would be awesome!! 

PS: For now we have support for `pydantic<2` but I am working on a PR to support it and drop `pydantic 1`. I expect that will be finishes in some weeks. If you want to add this feature now and the refactor it you are also welcome
