### ISSUE TITLE
dataclasses.field not rendered correctly in conjunction with AvroRecord

### ISSUE THREAD

**Issue by mozTheFuzz** [marcosschroh/dataclasses-avroschema#411]
**Describe the bug**
I have the following code
```python
from dataclasses_avroschema.faust import AvroRecord
from dataclasses import dataclass, field
from uuid import uuid4


@dataclass
class TestA(AvroRecord):
    id: str = field(default_factory=lambda: str(uuid4()))


print(TestA().id)


@dataclass
class TestB:
    id: str = field(default_factory=lambda: str(uuid4()))


print(TestB().id)
```

the output for TestA().id: 
`Field(name=None,type=None,default=<dataclasses._MISSING_TYPE object at 0x102b0a020>,default_factory=<function TestA.<lambda> at 0x102aefac0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=<dataclasses._MISSING_TYPE object at 0x102b0a020>,_field_type=None)`

the output for TestB().id:
`4cf4a448-c964-40ef-8e5c-73ba47af7795`

The output of TestA().id suggests that somehow inheriting AvroRecord will break the dataclasses.field(...)

**To Reproduce**

I am using 3.10 with the latests commit of this library

**Expected behavior**

I expect the TestA().id to return a str(uuid4()) result instead of Field(...)

**Comment by marcosschroh** [comment]
Thanks for reporting the issue @mozTheFuzz

What you are doing is not correct because you can not use all the `dataclasses` features with `faust`, for example `dataclasses.field`. The reason is  that `Faust` implements its own why of providing `defaults` and field validation, defaults, etc. Check the [Faust Fields section](https://faust-streaming.github.io/faust/userguide/models.html#fields).

Following your approach what you should do is:

```python
from dataclasses_avroschema.faust import AvroRecord
from faust.models.fields import StringField
from uuid import uuid4

class TestA(AvroRecord):
    id: str = StringField(default=uuid4(), required=False)

TestA()
# Out[35]: <TestA: id=UUID('ea3bf59c-5030-4325-a0ed-1cad4253e0d2')>
```

PS: The [documentation](https://marcosschroh.github.io/dataclasses-avroschema/faust_records/) is not up to date so I will update it.

**Comment by mozTheFuzz** [comment]
> Thanks for reporting the issue @mozTheFuzz
> 
> What you are doing is not correct because you can not use all the `dataclasses` features with `faust`, for example `dataclasses.field`. The reason is that `Faust` implements its own why of providing `defaults` and field validation, defaults, etc. Check the [Faust Fields section](https://faust-streaming.github.io/faust/userguide/models.html#fields).
> 
> Following your approach what you should do is:
> 
> ```python
> from dataclasses_avroschema.faust import AvroRecord
> from faust.models.fields import StringField
> from uuid import uuid4
> 
> class TestA(AvroRecord):
>     id: str = StringField(default=uuid4(), required=False)
> 
> TestA()
> # Out[35]: <TestA: id=UUID('ea3bf59c-5030-4325-a0ed-1cad4253e0d2')>
> ```
> 
> PS: The [documentation](https://marcosschroh.github.io/dataclasses-avroschema/faust_records/) is not up to date so I will update it.

Thank you.
I dug around after posting this and found out about StringField.
😂😂😂😂😂😂😂😂😂
