### ISSUE TITLE
Add support for Pydantic V2

### ISSUE THREAD

**Issue by marcosschroh** [marcosschroh/dataclasses-avroschema#415]
**Is your feature request related to a problem? Please describe.**
Because `pydantic v2` has been released we want to add support for it.

**Additional context**
Pydantic v1 support will be dropped. For users that are using `dataclasses` this won't be a problem. We want to increase a `major` version on this feature and then have a special branch for  `pydantic v1` support  in case that we need a hot fix (this should be only *patch changes*)

**Comment by marcosschroh** [comment]
Related to https://github.com/marcosschroh/dataclasses-avroschema/issues/381 and https://github.com/marcosschroh/dataclasses-avroschema/issues/200

**Comment by michal-rogala** [comment]
Isn't this too fast to limit v1 support only to patches? V2 is only for 2 months "on the market" and it takes time for projects to migrate to it. Did you consider to use for example `avrodantic2` namespace and have support for both?

I doubt pydantic v1 goes away soon, too many products depend on it.

**Comment by bkushnir2** [comment]
One aspect is missing in the initial request: lack of v2 support in dataclasses-avroschema blocks migration of the projects which depend on this package. You cannot have both pytdantic v1 and v2 in the same project.
**But** there is a cheap solution. The solution is to benefit from the fact that pydantic v2 contains also v1 version in a separate folder.
So, the first step for dataclasses-avroschema would be to use the following code :
```python
try:
    from pydantic import v1 as pydantic # for pydantic v2
except ImportError:
    import pydantic # for pydantic v1
```
This will suport both v1 and v2 of pydantic.
See https://github.com/pydantic/pydantic/discussions/4649 for discussion.

**Comment by marcosschroh** [comment]
@bkushnir2 totally agree, we need to support pydantic v2 asap. 

Having pydantic v1 code in the v2 is nice but unfortunatly is not as easy as it seems. Changing the imports does not solve the issue because the internal API and Fiedls have changed. 

I am working on a PR to:

1. Isolate the `pydantic` functionalities inside `dataclasses-avroschemas` and then the code changes will be easier to adapt inside the namespace `dataclasses_avroschemas.pydantic`
2. Make all `AvroModel` attributes private to avoid [shadow warnings](https://github.com/pydantic/pydantic/discussions/2410)

PS: People using `pydantic` will have to update the imports from `dataclasses_avroschemas.avrodantic` to `dataclasses_avroschemas.pydantic`

**Comment by dabdada** [comment]
Whats the progress here? Is there an estimation when this is finished?

Let me please know if you need any help on this. I am very interested in using this with pydantic v2 as soon as possible.

**Comment by marcosschroh** [comment]
Hi all.

Still in progress. I have some test failing and I need to deal with some LogicalTypes (uuid). Here are the changes https://github.com/marcosschroh/dataclasses-avroschema/compare/feat/add-pydantic-v2?expand=1
