### ISSUE TITLE
Fields of type `None` raise error on schema generation or have duplicated type in schema

### ISSUE THREAD

**Issue by Prometheus3375** [marcosschroh/dataclasses-avroschema#424]
# Describe the bug
If a class has field with type `None`, the schema generation fails.
If a class has field with type `NoneType` and default value `None`, the schema of this field has type `["null", "null"]`.

# To Reproduce

## Issue 1
```python
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass

@dataclass
class Data(AvroModel):
    f1: None

Data.avro_schema()  # ValueError: Type None is unknown.
```

## Issue 2

```python
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass
from types import NoneType

@dataclass
class Data(AvroModel):
    f1: NoneType = None

Data.avro_schema()
# type array has duplicates
# '{"type": "record", "name": "Data", "fields": [{"name": "f1", "type": ["null", "null"], "default": null}]}'
```

# Expected behavior

No error in issue 1.
Both issues must have type `null` for field `f1`.

# Why someone would need null field

The presence of a field can be required by Python protocols, but some certain classes make no use of it.

```python
from typing import Protocol, TypeVar
from dataclasses import dataclass

T = TypeVar('T', covariant=True)


class DataProto(Protocol[T]):
    @property
    def f1(self, /) -> int: ...
    @property
    def f2(self, /) -> str: ...
    @property
    def f3(self, /) -> T: ...


@dataclass
class Data1:
    f1: int
    f2: str
    f3: list[int]


@dataclass
class Data2:
    f1: int
    f2: str


@dataclass
class Data3:
    f1: int
    f2: str
    f3: None = None


def process_data(data: DataProto, /) -> None: pass


process_data(Data1(1, '1', [1]))  # passes type check
process_data(Data2(1, '1'))  # fails type check
process_data(Data3(1, '1'))  # passes type check

# mypy errors:
# main.py:40: error: Argument 1 to "process_data" has incompatible type "Data2"; expected "DataProto[Any]"  [arg-type]
# main.py:40: note: "Data2" is missing following "DataProto" protocol member:
# main.py:40: note:     f3
```

**Comment by marcosschroh** [comment]
@Prometheus3375 `Null` are always used in `unions`. A field can not be just `null`. It is not possible

**Comment by Prometheus3375** [comment]
The first issue can be easily fixed by updating [`INMUTABLE_FIELDS_CLASSES`](https://github.com/marcosschroh/dataclasses-avroschema/blob/cd62071cbc3bae047ba5bfec67d46dfd10861942/dataclasses_avroschema/fields/mapper.py#L13):

```python
INMUTABLE_FIELDS_CLASSES: dict[type | str | None, type] = {
    bool: fields.BooleanField,
    int: fields.LongField,
    types.Int32: fields.IntField,
    float: fields.DoubleField,
    types.Float32: fields.FloatField,
    bytes: fields.BytesField,
    str: fields.StringField,
    None: fields.NoneField,
    type(None): fields.NoneField,
}
```
As far as I understood from the test structure, no test should be updated then. Although I noticed that `null` type is not checked for invalid default values.

The issue with the duplicated type can be fixed via `get_avro_type` overwrite in [`NoneField`](https://github.com/marcosschroh/dataclasses-avroschema/blob/cd62071cbc3bae047ba5bfec67d46dfd10861942/dataclasses_avroschema/fields/fields.py#L126C9-L126C9):

```python
@dataclasses.dataclass
class NoneField(ImmutableField):
    @property
    def avro_type(self) -> str:
        return field_utils.NULL

    def get_avro_type(self) -> str:
        return self.avro_type
```

---

> It is not possible.

Having null fields in AVRO is not prohibited. Currently, `dataclasses_avrochema` serializes and deserealizes such fields with no issues. Although, using `types.NoneType` or `type(None)` in type annotations is not a common practice, as `None` in most cases converts to `types.NoneType`.

**Comment by marcosschroh** [comment]
Can you share the `avro` documentation where only`null` fields are used? Can you describe in which situation you should use only null (taking into account that always null will be received?

**Comment by Prometheus3375** [comment]
`avro` [documentation](https://avro.apache.org/docs/1.11.1/specification/) only states that `null` is a primitive type and for a field with such type provides an example of the default value which is `null`. The documentation does not have examples of schemas with `null` fields.

I do not think there is a case where `null` is the only option. `false` is also encoded as `b'\x00'`, but in situations where a value is just a placeholder I prefer singleton types such as `null`.

I've just checked and found out that `None` is not converted to `types.NoneType` when used inside builtin generic types. For example, `dict[str, None].__args__` returns `(str, None)` (`typing.Dict` converts to `types.NoneType`). Having `dict[str, None]` type in `AvroModel` subclass will also lead to an error upon schema generation.

```python
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass


@dataclass
class Data(AvroModel):
    f1: dict[str, None]


Data.avro_schema()  # ValueError: Type None is unknown.
```

Since Python 3.7 dictionary can be used as an ordered set, because unlike `set` keys inside `dict` preserve the order of insertion. When using `dict` as a set, values does not matter and `None` can be easily used. `dict` also have a special constructor `dict.fromkeys(iterable, value=None)` which perfectly suits this case. Of course, using `dict` as a set is not memory efficient, but performance-wise this is best solution from the standard library.

Using `dict[T, None]` in `AvroModel` subclasses is not efficient at all, but during experiments and testing it is OK to use before implementing more efficient solution.
