### ISSUE TITLE
Validation with enums fails

### ISSUE THREAD

**Issue by godlessendeavor** [marcosschroh/dataclasses-avroschema#426]
**Describe the bug**
Using latest version (0.49) I tried to validate the schema that would be generated by a class containing an Enum attribute but it fails to validate when using a correct enum value.

**To Reproduce**
Example:
```
from dataclasses import dataclass
from enum import Enum

from dataclasses_avroschema import AvroModel


class SomeEnum(Enum):
    a = "a"
    b = "b"


@dataclass
class Example(AvroModel):
    en: SomeEnum

def test_enum():
    ex = Example(SomeEnum.a)
    ex.validate()
```

**Expected behavior**
Validation succeeds

**Comment by marcosschroh** [comment]
Hi @godlessendeavor this is not how `enums` works. You need to specify the enum value when creating  the instance. In this case `SomeEnum.a.value`. 

```python
ex = Example(SomeEnum.a)
ex.validate()
```
