### ISSUE TITLE
PydanticImportError: `pydantic:ConstrainedInt` has been removed in V2.

### ISSUE THREAD

**Issue by svillegas-cdd** [marcosschroh/dataclasses-avroschema#436]
**Describe the bug**
I'm having this error when I try to start my app after update to `pydantic==2.3.0` and `dataclasses_avroschema==0.51.0`
```
    from dataclasses_avroschema.pydantic.main import AvroBaseModel
../lib/python3.10/site-packages/dataclasses_avroschema/pydantic/__init__.py:2: in <module>
    from .mapper import PYDANTIC_INMUTABLE_FIELDS_CLASSES, PYDANTIC_LOGICAL_TYPES_FIELDS_CLASSES
../lib/python3.10/site-packages/dataclasses_avroschema/pydantic/mapper.py:28: in <module>
    pydantic.ConstrainedInt: fields.ConstrainedIntField,
../lib/python3.10/site-packages/pydantic/__init__.py:210: in __getattr__
    return _getattr_migration(attr_name)
../lib/python3.10/site-packages/pydantic/_migration.py:295: in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
E   pydantic.errors.PydanticImportError: `pydantic:ConstrainedInt` has been removed in V2.
E   
E   For further information visit https://errors.pydantic.dev/2.3/u/import-error
```

I see that the `mapper` in `dataclasses_avroschema/pydantic/mapper.py` creates a `dict` with the field `pydantic.ConstrainedInt` and other fields that are not longer in pydantic as they are imported in `dataclasses_avroschema/pydantic/__init__.py` they make raise the error

**To Reproduce**
*  Updated to `pydantic==2.3.0`
*  Update to `dataclasses_avroschema==0.51.0`
* Import AvroBaseModel: `from dataclasses_avroschema.pydantic.main import AvroBaseModel`
* Start the app

**Expected behavior**
The app to start without import errors

**Comment by marcosschroh** [comment]
@svillegas-cdd we are aware of this issue https://github.com/marcosschroh/dataclasses-avroschema/issues/415. You can only use this library with `pydantic v1`, in coming weeks support for `pydantic v2` will be added
