### ISSUE TITLE
dc-avro cli strict validate

### ISSUE THREAD

**Issue by joaoe** [marcosschroh/dataclasses-avroschema#441]
**Describe the solution you'd like**

In my project we have a couple schemas shared between some python and java projects.

The schemas are maintained manually, and used to generate java classes, or the opposite in another project, generate the json schema from python class models using dataclasses-avroschema and then compare with the expected one.

However, that manually maintained schema has some "bugs", basically, properties not part of the avro specification. These are ignored when generatingthe Java classes, which is why the bugs are there, but not while reversing that process with the python project.

Therefore, it would be great if dc-avro could function as a sort of validator or linter, warning about stuff that is not recognized.

For instance
```
{
  "fields": [
    {
      "default": null,
      "name": "messages",
      "type": [
        "null",
        {
          "default": [],
          "items": "string",
          "type": "array"
        }
      ]
    }
  ],
  "name": "ABC1",
  "namespace": "com.example.xxx",
  "type": "record"
}
```
has two defaults, one inside type which is not valid I think.

`dc-avro` could be called with a `--strict` switch which would fail validation for any such structural fail.
```
$  dc-avro validate-schema --strict --path schema.avsc
```

Other kinds of fails would be for instance, objects with empty fields, dupliate "null" in type, etc.

**Describe alternatives you've considered**
So far I have not found an avro schema linter anywhere.

**Comment by marcosschroh** [comment]
I will try to add it in `dc-avro`.

**Comment by marcosschroh** [comment]
Closing due inactivity
