### ISSUE TITLE
serialize() doesn't work if there is field value with None

### ISSUE THREAD

**Issue by lcalviny** [marcosschroh/dataclasses-avroschema#45]
serialize() doesn't work if there is field value with None:

data_user = {
    "name": None,
    "age": 20,
    "addresses": [address],
}

# create an User instance
user = User(**data_user)

user.serialize()

    fastavro.schemaless_writer(file_like_output, schema, payload)
  File "fastavro\_write.pyx", line 635, in fastavro._write.schemaless_writer
  File "fastavro\_write.pyx", line 335, in fastavro._write.write_data
  File "fastavro\_write.pyx", line 285, in fastavro._write.write_record
  File "fastavro\_write.pyx", line 313, in fastavro._write.write_data
  File "fastavro\_write.pyx", line 125, in fastavro._write.write_utf8
  File "fastavro\_six.pyx", line 25, in fastavro._six.py3_utob
TypeError: encoding without a string argument

**Comment by marcosschroh** [comment]
Hi @lcalviny ,

Thanks for reporting the issue. I will take a look and try to fix it asap. `Pull requests` are welcome as well.

**Comment by marcosschroh** [comment]
I think [here](https://github.com/marcosschroh/dataclasses-avroschema/blob/master/tests/serialization/test_primitive_types_serialization.py#L44) is a test doing what you are trying to do. Can you take a look?

**Comment by lcalviny** [comment]
Excellent! it works perfect now. I will do more testings and let you know if there is any issue. 

Thanks your quick turnaround,

**Comment by lcalviny** [comment]
Hi Marcos,

just found if there is no default value in class attributes, but put None
in the instance variable, will get error.

 "name": None

@dataclass
class Address(AvroModel):
    "An Address"
    street: str
    street_number: int

@dataclass
class User(AvroModel):
    "User with multiple Address"
    name: str
    age: int
    addresses: typing.List[Address]

address_data = {
    "street": "street",
    "street_number": 10,
}

# create an Address instance
address = Address(**address_data)

data_user = {
    "name": None,
    "age": 20,
    "addresses": [address],
}

# create an User instance
user = User(**data_user)

a = user.to_json()
# b = json.dumps(a)



TypeError: encoding without a string argument

**Comment by marcosschroh** [comment]
What are you doing must fail because n the class definition you have `name: str` (no optional), but should fail at the moment that you perform the user creation or when you execute `to_json`. Also, I am seeing that the decorator is not correct, should be `@dataclass`. Maybe you have a typo. Can you confirm/

**Comment by lcalviny** [comment]
@dataclass
class Address(AvroModel):
    "An Address"
    street: str
    street_number: int

@dataclass
class User(AvroModel):
    "User with multiple Address"
    name: str
    age: int
    addresses: typing.List[Address]

address_data = {
    "street": "street",
    "street_number": 10,
}

# create an Address instance
address = Address(**address_data)

data_user = {
    "name": None,
    "age": 20,
    "addresses": [address],
}

# create an User instance
user = User(**data_user)

print(user.to_json())



in class definition, name: str. and in data_user "name": None. get the
error below:
    fastavro.schemaless_writer(file_like_output, schema, payload)
  File "fastavro\_write.pyx", line 635, in fastavro._write.schemaless_writer
  File "fastavro\_write.pyx", line 335, in fastavro._write.write_data
  File "fastavro\_write.pyx", line 285, in fastavro._write.write_record
  File "fastavro\_write.pyx", line 313, in fastavro._write.write_data
  File "fastavro\_write.pyx", line 125, in fastavro._write.write_utf8
  File "fastavro\_six.pyx", line 25, in fastavro._six.py3_utob
TypeError: encoding without a string argument

but it works in 0.14.0.

**Comment by marcosschroh** [comment]
@lcalviny 

Makes sense the error, because the `avro schema` that is generated from the python class does not allow name as `null`, must be a string. If you want that behaviour, you must either use `name: typing.Optional[str]` or `name: str = None`. Anyway, I realize that the documentation is missing for `typing.Optional`, so is a good moment to include it.

**Comment by lcalviny** [comment]
if default all the class attributes to None, but only pass 
data_user = {
    "age": 20,
}

but get error: TypeError: object of type 'NoneType' has no len()


@dataclass
class Address(AvroModel):
    "An Address"
    street: typing.Optional[str]  
    street_number: int  

@dataclass
class User(AvroModel):
    "User with multiple Address"
    name: str = None
    age: int = None
    addresses: typing.List[Address] = None

address_data = {
    "street": "street",
    "street_number": 10,
}

# create an Address instance
address = Address(**address_data)

data_user = {
    # "name": None,
    "age": 20,
    # "addresses": [address],
}

# create an User instance
user = User(**data_user)
