### ISSUE TITLE
if class instance has default value, there is issue with result

### ISSUE THREAD

**Issue by lcalviny** [marcosschroh/dataclasses-avroschema#47]
@dataclass
class User(AvroModel):
    "User with multiple Address"
    name: str = None
    age: int = None
    addresses: typing.List[Address] 

address_data = {
    "street": "street",
    "street_number": 10,
}

# create an Address instance
address = Address(**address_data)

data_user = {
    # "name": None,
    # "age": 20,
    "addresses": [address],
}

# create an User instance
user = User(**data_user)

a = user.to_json()

result: 
{'name': None, 'age':  {'int': 20}, 'addresses': [{'street': 'street', 'street_number': 10}]}

you can see age is {'int':20} instead of 'age':20

**Comment by marcosschroh** [comment]
Hi @lcalviny ,

Yes, the serialization and json features are in a beta state. I will try to fix all the issues asap. 

Thanks

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/48

You can check it with the latest version `0.14.2`
