### ISSUE TITLE
How can I add documentation for field

### ISSUE THREAD

**Issue by AbhinavPelapudi** [marcosschroh/dataclasses-avroschema#50]
I know i can add documentation for Record. ButI want to add documentation for each field in a data-class (Record) can I know how can i add it ?

Example 
@dataclass
class User(Faust.Record, AvroModel):
     name: str
     age:int

In the above example i wanted to add documentation for fields (name, age) in a User record. is there a way to do it? If so can you please provide an example on how to do it? Thanks

**Comment by aaronfowles** [comment]
You can use the `dataclasses.field` descriptor's metadata to add arbitrary key-value pairs at the field level.
```python
import typing
from dataclasses import dataclass, field

from dataclasses_avroschema import AvroModel, types

@dataclass
class User(AvroModel):
    "An User"
    name: str = field(metadata={'doc': 'bar'})
    age: int = field(metadata={'doc': 'foo'})

User.avro_schema()

'{
    "type": "record",
    "name": "User",
    "doc": "An User",
    "fields": [
        {"name": "name", "type": "string", "doc": "bar"},
        {"name": "age", "type": "int", "doc": "foo"}
    ]
}'
```

**Comment by marcosschroh** [comment]
Thanks for the suggestion @aaronfowles .

I think we do not have documented this feature. Does someone of you want to send a `PR` for this? Maybe should be added in `Fields Specification` section.

**Comment by aaronfowles** [comment]
> Thanks for the suggestion @aaronfowles .
> 
> I think we do not have documented this feature. Does someone of you want to send a `PR` for this? Maybe should be added in `Fields Specification` section. 

Yes, good idea - I'll put a PR together soon!

**Comment by marcosschroh** [comment]
Hi @AbhinavPelapudi 

Sorry for the delay. I have created a `PR` that will allow what you need. Please take a look https://github.com/marcosschroh/dataclasses-avroschema/pull/56

**Comment by AbhinavPelapudi** [comment]
No Problem. Thank you @marcosschroh

**Comment by marcosschroh** [comment]
Example:

```python
@dataclass
class User(AvroModel):
    "An User"
   age: typing.Union[None, typing.List[str]] = None

User.avro_schema()

'{"type": "record", "name": "User", "fields": [{"name": "something", "type": ["null", {"type": "array", "items": "string", "name": "something"}], "default": "null"}], "doc": "An User"}'
```

**Comment by AbhinavPelapudi** [comment]
Thanks alot @marcosschroh
