### ISSUE TITLE
Incorrect import command in the readme file

### ISSUE THREAD

**Issue by anneum** [marcosschroh/dataclasses-avroschema#508]
**Describe the bug**
Either I'm missing something fundamental or the example for use with Pydantic in the [readme ](https://github.com/marcosschroh/dataclasses-avroschema?tab=readme-ov-file#pydantic-integration) is wrong.

```python
from dataclasses_avroschema.avrodantic import AvroBaseModel
```
``ModuleNotFoundError: No module named 'dataclasses_avroschema.avrodantic'``

It works with the following import as written [here](https://marcosschroh.github.io/dataclasses-avroschema/pydantic/):
```python
from dataclasses_avroschema.pydantic import AvroBaseModel
```

**Expected behavior**
The import is successful.

**Comment by anneum** [comment]
If this is indeed a mistake, I have created a pull request with a fix: https://github.com/marcosschroh/dataclasses-avroschema/pull/509

**Comment by marcosschroh** [comment]
Yes, it is a mistake. Thanks.
