### ISSUE TITLE
typing.Optional[typing.List[int]] field fails during serialization

### ISSUE THREAD

**Issue by maciejjaskowski** [marcosschroh/dataclasses-avroschema#51]
```
from dataclasses_avroschema import AvroModel
import typing
from dataclasses import dataclass, field


@dataclass
class X(AvroModel):
    y: typing.Optional[typing.List[int]]

X.avro_schema()
```
Fails with error:
```
AttributeError: type object 'list' has no attribute 'avro_schema_to_python'
```

**Comment by marcosschroh** [comment]
@maciejjaskowski thanks for reporting the issue. I will try to fix this asap.

**Comment by marcosschroh** [comment]
@maciejjaskowski I have fixed the issue. Please try the latest version `0.14.4`. Also, you can find the example in the [doc](https://marcosschroh.github.io/dataclasses-avroschema/complex_types/)
