### ISSUE TITLE
typing extensions not installed when using Python > 3.8

### ISSUE THREAD

**Issue by Oskar-Bonde** [marcosschroh/dataclasses-avroschema#540]
**Describe the bug**
typing extensions is not a required dependency when using Python > 3.8. So when using Python > 3.8 an import error is raised.

**To Reproduce**
Install dataclasses-avroschema using Python > 3.8. Make sure no other package is installing typing-extensions. Import error will be raised when trying to use AvroModel because of the following import: from typing_extensions import get_args.

**Expected behavior**
No import error. 

Fix by updating [pyproject.toml](https://github.com/marcosschroh/dataclasses-avroschema/blob/master/pyproject.toml), remove python version requirement from typing-extensions.

**Comment by marcosschroh** [comment]
Closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/541
