### ISSUE TITLE
Default null record 

### ISSUE THREAD

**Issue by chapm250** [marcosschroh/dataclasses-avroschema#57]
I'm trying to create a nested record with a default value of null. I tried something like this but am getting a `AttributeError: 'NoneType' object has no attribute 'avro_schema_to_python'` error 

```
import typing

from dataclasses_avroschema import AvroModel, types


class foobar(AvroModel):
    Name: str = None
    Parent: int = None


class foo(AvroModel):
    foobar: foobar = None


print(foo.avro_schema())
```

**Comment by marcosschroh** [comment]
@chapm250 thanks,

I will try to fix this asap

**Comment by chapm250** [comment]
Ahh I thought I was just doing it wrong, thanks for the awesome project!

**Comment by marcosschroh** [comment]
Hi @chapm250 

I have figured out that is not a bug in the library, is related to the attribute name. Somehow, the type `foobar` makes reference  to itself. (foobar type actually is pointing to `foobar` which is None). If you try to assign a different default value, for example `foobar: foobar = 10` you will have a similar error: `AttributeError: 'int' object has no attribute 'avro_schema_to_python'`

The correct way to do it is using a different name or even better is respecting the convention for class names and attributes:

```python
import typing

from dataclasses_avroschema import AvroModel, types

class Foobar(AvroModel):
    name: str = None
    parent: int = None


class Foo(AvroModel):
    foobar: Foobar = None

Foo.avro_schema()

'{"type": "record", "name": "Foo", "fields": [{"name": "foobar", "type": ["null", {"type": "record", "name": "Foobar", "fields": [{"name": "name", "type": ["null", "string"], "default": "null"}, {"name": "parent", "type": ["null", "int"], "default": "null"}], "doc": "Foobar(name: str = None, parent: int = None)"}], "default": "null"}], "doc": "Foo(foobar: __main__.Foobar = None)"}'
```

**Comment by chapm250** [comment]
That worked for me, thanks for looking into this
