### ISSUE TITLE
Handling Additional Fields in Dataclasses

### ISSUE THREAD

**Issue by Christos-Hadjinikolis** [marcosschroh/dataclasses-avroschema#595]
## Is your feature request related to a problem? Please describe.**
I've observed that dataclasses-avroschema allows the instantiation of Python dataclasses with additional fields that are not defined in the Avro schema. This behavior can lead to data inconsistencies, as the resulting dataclass instances may carry data not intended by the schema.

**Current behaviour** 
```python
from dataclasses_avroschema import AvroModel

@dataclass
class Example(AvroModel):
    field_a: str
    field_b: int

extra_data = {
    "field_a": "value",
    "field_b": 123,
    "field_c": "unexpected"  # Not defined in the Example dataclass
}

example_instance = Example(**extra_data)
# Unexpectedly, example_instance includes field_c
```

## Describe the solution you'd like  
I propose adding an option for stricter instantiation of dataclasses, where fields not defined in the Avro schema are ignored, aligning with behavior seen in other languages like Java.

**Intended Behavior Example:**
```python
from dataclasses_avroschema import AvroModel

@dataclass
class Example(AvroModel):
    field_a: str
    field_b: int

extra_data = {
    "field_a": "value",
    "field_b": 123,
    "field_c": "unexpected"
}

example_instance = Example.strict(**extra_data)
# field_c is ignored, ensuring example_instance adheres strictly to the Avro schema
```

## Describe alternatives you've considered
An alternative could be filtering extra fields manually before instantiation, but it's less efficient and prone to errors. Another is subclassing each dataclass to override the constructor, but this adds maintenance complexity.

## Additional context
Aligning dataclasses-avroschema with the behavior of other Avro implementations would enhance cross-language schema compatibility and uphold data integrity. It would ensure Python dataclasses reflect their Avro schema more precisely, especially important in projects with rigorous data consistency requirements.

**Comment by marcosschroh** [comment]
Hi @Christos-Hadjinikolis 

It should not be possoble to create a `dataclass` instance with a field that is not defined. If I run your example I get the `TypeError`, which makes sense.

```python
In [2]: from dataclasses import dataclass

In [3]: from dataclasses_avroschema import AvroModel
   ...: 
   ...: @dataclass
   ...: class Example(AvroModel):
   ...:     field_a: str
   ...:     field_b: int
   ...: 
   ...: extra_data = {
   ...:     "field_a": "value",
   ...:     "field_b": 123,
   ...:     "field_c": "unexpected"  # Not defined in the Example dataclass
   ...: }
   ...: 
   ...: example_instance = Example(**extra_data)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 14
      6     field_b: int
      8 extra_data = {
      9     "field_a": "value",
     10     "field_b": 123,
     11     "field_c": "unexpected"  # Not defined in the Example dataclass
     12 }
---> 14 example_instance = Example(**extra_data)

TypeError: Example.__init__() got an unexpected keyword argument 'field_c'
```

This is a how `dataclasses` works. Which `python` version are you using?

**Comment by Christos-Hadjinikolis** [comment]
Naively, I did not run the example I sent you 'cause the code I have is failing on the autogenerated classes I have and so I thought that this is how it behaves, which struct me as awkward. 

Investigating and trying to understand why this is happening. Thanks for the prompt response. 

I ll get back to you asap.

**Comment by Christos-Hadjinikolis** [comment]
Regardless, the extra field should not be causing a failure though right? It should simply be ignored, as this is a non-breaking, backwards-compatible schema change, not?

**Comment by Christos-Hadjinikolis** [comment]
Ok, I was finally able to reproduce: 
```python
import dataclasses
import pytest
from dataclasses_avroschema import AvroModel


@dataclasses.dataclass
class SubExample(AvroModel):
    field_c: str
    field_d: int


@dataclasses.dataclass
class Example(AvroModel):
    field_a: str
    field_b: SubExample


class TestNestedDataclassInstantiation:
    @pytest.mark.unit
    def test_nested_extra_fields_with_wrong_way_to_instantiate_object(self):
        # Given
        sub_example_data = {
            "field_c": "test",
            "field_d": 123,
            "extra_field": "unexpected"  # Not defined in SubExample dataclass
        }

        # When
        example_instance = Example(field_a="value", field_b=sub_example_data)   # Wrong way to instantiate an Example object

        # No error is raised! The extra field is ignore
        print(example_instance)

    @pytest.mark.unit
    def test_nested_extra_fields_with_right_way_to_instantiate_object(self):
        # Given
        sub_example_data = {
            "field_c": "test",
            "field_d": 123,
            "extra_field": "unexpected"  # Not defined in SubExample dataclass
        }

        # When
        with pytest.raises(TypeError):
            example_instance = Example(field_a="value", field_b=SubExample(**sub_example_data))   # Right way to instantiate an Example object
```

Admittedly, I should not have been instantiating a dataclass object like that (first example). I fixed my code as per the second test, but maybe installing a prevention mechanism would be useful?

**Comment by Christos-Hadjinikolis** [comment]
More importantly, what do you think about [this](https://github.com/marcosschroh/dataclasses-avroschema/issues/595#issuecomment-2046128136)?

**Comment by marcosschroh** [comment]
> Regardless, the extra field should not be causing a failure though right? It should simply be ignored, as this is a non-breaking, backwards-compatible schema change, not?

A failure is the expected  `python` behavior, unrelated to this library `dataclasses-avroschema`. If you run the code **without** using `dataclasses-avroschema` it will fail as well:

```python
In [2]: from dataclasses import dataclass

# Not using AvroModel
class Example:
   field_a: str
   field_b: int

extra_data = {
    "field_a": "value",
    "field_b": 123,
    "field_c": "unexpected"  # Not defined in the Example dataclass
}

example_instance = Example(**extra_data)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], line 14
      6     field_b: int
      8 extra_data = {
      9     "field_a": "value",
     10     "field_b": 123,
     11     "field_c": "unexpected"  # Not defined in the Example dataclass
     12 }
---> 14 example_instance = Example(**extra_data)

TypeError: Example.__init__() got an unexpected keyword argument 'field_c'
```

Also, the `avro schema` generated is unrelated to the data that is used when creating `class instances`.

**Comment by marcosschroh** [comment]
> Admittedly, I should not have been instantiating a dataclass object like that (first example). I fixed my code as per the second test, but maybe installing a prevention mechanism would be useful?

Yes, you must use `python dataclasess`  like in your `test_nested_extra_fields_with_right_way_to_instantiate_object` test. The problem with dataclasses is that they are not really smart. If you want to something smarter then you can use `pydantic`. Following your example, the extra field is ignored:

```python
In [13]: from pydantic import BaseModel

class Example(BaseModel):
    field_a: str
    field_b: int

extra_data = {
    "field_a": "value",
    "field_b": 123,
    "field_c": "unexpected"  # Not defined in the Example
}

example_instance = Example(**extra_data)

In [15]: example_instance
Out[15]: Example(field_a='value', field_b=123)
```

This library has [pydantic support](https://marcosschroh.github.io/dataclasses-avroschema/pydantic/) as well.
