### ISSUE TITLE
Convert homogeneously typed Literals into ENUMs

### ISSUE THREAD

**Issue by kevinjacobs-delfi** [marcosschroh/dataclasses-avroschema#596]
**Is your feature request related to a problem? Please describe.**
I am translating a large corpus of Avro schemas into Pydantic V2 models and our convention is to encode simple string enums as Literal types in those models.  Currently, the `dataclasses-avroschema` translates homogeneously typed Literals into a field of that type.  

e.g. 
```python
class A(AvroBaseModel):
    foo: Literal["a", "b", "c"]
```
yields this schema:
```avro
{
    "type": "record", 
    "name": "A", 
    "fields": [{"name": "foo", "type": "string"}]
}
```

**Describe the solution you'd like**
The current behavior is backward compatible, since it widens the range of valid values.  But it also means that the constraint on values is lost for other users of these schemas unless using them mediated via our Pydantic models.   It would be great if we could add an config value or annotation that changes this behavior locally or globally to generate Avro ENUMs for such Literals.

```avro
{
    "type": "record", 
    "name": "A", 
    "fields": [{"name": "foo", "type": {"type": "enum", "name": "FooValues", "symbols": ["a", "b", "c"]}}]
}
```

**Describe alternatives you've considered**
We could, in theory, switch from using `Literal` to using `StrEnum`, but would require updating a huge amount of related code to do so.  Our data governance team would probably recommend switching to another Avro/Pydantic mapping library instead.

**Comment by marcosschroh** [comment]
Hi @kevinjacobs-delfi 

It makes sense that `Literals` with ONLY `strings` primitive values are represented as `enum` in `avro`. This might require some extra work to make sure that conversion from `avro schemas` to `models` also works, so `avro enums` that were generated with `pythonn Literals` will generate `Literals` rather then  `python Enum`.

**Comment by marcosschroh** [comment]
II have added a new option called [convert_literal_to_enum](https://marcosschroh.github.io/dataclasses-avroschema/pr-preview/pr-608/complex_types/#enums-from-typingliteral-of-strigns) to convert Literal strings to avro enum.

**Comment by kevinjacobs-delfi** [comment]
Great!  I'll give it a try and let you know.
