### ISSUE TITLE
Support for typing.Union, avro logical types and interoperation with faust

### ISSUE THREAD

**Issue by slawak** [marcosschroh/dataclasses-avroschema#6]
Hi,

i took the liberty to fork your code and take a shoot at some improvements i needed for my work.
The aim was to be able to use complex faust models for schema generation in such a way that the resulting schema is compatible with faust.Record.to_representation() and faust.Record.from_data() operations. 
Second goal was to produce a schema which is compatible with fastavro. Fastavro does not handle nested schemas very well as they pose a high risk of multiple definition of the same records. I implemented a crude way to traverse a final schema and flatten it.
The code changes are in 
[slawak/dataclasses-avroschema:feature/faust-records](/slawak/dataclasses-avroschema/tree/feature/faust-records)

Feel free to look at the result and improve upon it.

**Comment by marcosschroh** [comment]
Hi @slawak,

Please, be my guest! I will take a look. Super cool if we have support for `logical types` and `Union` and `Faust`.

Regarding to nested schemas, we have support for `OneToOne and `OneToManty`, but I do not remember how is the case with `Fastavro`. Maybe you had the same problem that I had with recursive schemas.

Shall we create separete PRs per feature/bug?

**Comment by marcosschroh** [comment]
I was taking a look the code and it looking good, but is hard to review it all together. Also, I have noticed that you took some ideas from the branch `feature/recursive-relationship-schemas` to do the recursive schemas 👍 :-)

I would like to have 3 pull request and then we can work case by case.

1. Pull request for `Logical Types`
2. Pull request for `Recursive Schemas` (and we can compare with my branch)
3. Faust Support

What do you think?

**Comment by marcosschroh** [comment]
closing this because we have added support for `recursive schemas`, `logical types`, `unions` and `faust`. 
 
You're more than welcome to check the last release and give some feedback.
