### ISSUE TITLE
Make enums inherit from str and enum.Enum in ModelGenerator.render

### ISSUE THREAD

**Issue by alxdrcirilo** [marcosschroh/dataclasses-avroschema#637]
**Is your feature request related to a problem? Please describe.**
Generating `Python classes` from an `avro schema` using `dataclasses-avroschema.ModelGenerator.render` method with the `model_type` argument set to `ModelType.AVRODANTIC` will render a Python class with the enum.

For example:
```python
class SomeEnum(enum.Enum):
    ...
```

**Describe the solution you'd like**
Since [enums in avro are always strings](https://avro.apache.org/docs/1.9.1/spec.html#Enums), it would be nice to have the aforementioned method render.

If we take the previous example:
```python
class SomeEnum(str, enum.Enum):
    ...
```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by marcosschroh** [comment]
Yes, it makes sense. We should do it regardless the `ModelType` that is used.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/652
