### ISSUE TITLE
null defaults for strings results in string nulls rather than avro nulls 

### ISSUE THREAD

**Issue by chapm250** [marcosschroh/dataclasses-avroschema#64]
```
import typing

from dataclasses_avroschema import AvroModel, types


class foo(AvroModel):
    foobar: str = None


print(foo.avro_schema())
```

Results in 
`{"type": "record", "name": "foo", "fields": [{"name": "foobar", "type": ["null", "string"], "default": "null"}], "doc": "foo(foobar: str = None)"}`

Where it should instead result in 
`{"type": "record", "name": "foo", "fields": [{"name": "foobar", "type": ["null", "string"], "default": null}], "doc": "foo(foobar: str = None)"}`

with "default": null not surrounded by strings

**Comment by marcosschroh** [comment]
Thanks @chapm250 . I am working in the fix

**Comment by marcosschroh** [comment]
@chapm250 please take a look the PR https://github.com/marcosschroh/dataclasses-avroschema/pull/65, I think this should be the correct behaviour

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/65

**Comment by chapm250** [comment]
lgtm, thanks!
