### ISSUE TITLE
Fails to import as `dateutil` is not listed as requirement

### ISSUE THREAD

**Issue by fsiola** [marcosschroh/dataclasses-avroschema#644]
**Describe the bug**
`dateutil` is used at https://github.com/marcosschroh/dataclasses-avroschema/blob/master/dataclasses_avroschema/dacite_config.py#L7 but is not listed as dependency.

The library them fails to load with `ModuleNotFoundError: No module named 'dateutil'`

**To Reproduce**

```shell
python -m venv .venv
source .venv/bin/activate
pip install dataclasses-avroschema==0.60.0
```

```python
from dataclasses_avroschema import AvroModel
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../dataclasses_avroschema/__init__.py", line 1, in <module>
    from .schema_generator import AvroModel  # noqa: F401 I001
  File ".../dataclasses_avroschema/schema_generator.py", line 11, in <module>
    from .dacite_config import generate_dacite_config
  File ".../dataclasses_avroschema/dacite_config.py", line 7, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
```

**Expected behavior**
Library imports correctly

**Comment by marcosschroh** [comment]
Ups! I forgot to included yesterday in the PR. I guess the tests passed because I installed with all the extra dependencies and it must be included on one of them. Thanks for reporting it !
