### ISSUE TITLE
When creating avro schema in camel case, nested class fields are not getting converted to proper camel case.

### ISSUE THREAD

**Issue by harikrishnan-dev** [marcosschroh/dataclasses-avroschema#700]
**Describe the bug**

I am trying to use the <ClassName>.avro_schema(case_type=case.CAMELCASE) to generate my schema in camelcase. But the function was not able to convert nested structures into Camel case.

**To Reproduce**
```
from dataclasses_avroschema.pydantic import AvroBaseModel
from dataclasses_avroschema import case

class Cat(AvroBaseModel):
    name: str
    created_by: str

class Fish(AvroBaseModel):
    name: str
    fins_count: int

class Animal(AvroBaseModel):
    tiger_animal: Cat | None = None
    whale_fish: Fish | None = None
    lion_animal : Cat | None = None


if __name__ =='__main__':
    print(Animal.avro_schema(case_type=case.CAMELCASE))
```

Steps to reproduce the behavior

**Expected behavior**

For the above code the result produced was 

`{"type": "record", "name": "Animal", "fields": [{"name": "tigerAnimal", "type": ["null", {"type": "record", "name": "Cat", "fields": [{"name": "name", "type": "string"}, {"name": "created_by", "type": "string"}]}], "default": null}, {"name": "whaleFish", "type": ["null", {"type": "record", "name": "Fish", "fields": [{"name": "name", "type": "string"}, {"name": "fins_count", "type": "long"}]}], "default": null}, {"name": "lionAnimal", "type": ["null", "Cat"], "default": null}]} 
`

The actual result should be where the fields created_by and fins_count should also be converted into `createdBy` and `finsCount`.

**Comment by marcosschroh** [comment]
Thanks for reporting the bug @harikrishnan-dev . I will try to fix it asap.

**Comment by harikrishnan-dev** [comment]
@marcosschroh any update on the above issue?

**Comment by marcosschroh** [comment]
Tomorrow I will start working on it

**Comment by marcosschroh** [comment]
With the new release the schema will be:

```json
{"type": "record", "name": "Animal", "fields": [{"name": "tigerAnimal", "type": ["null", {"type": "record", "name": "Cat", "fields": [{"name": "name", "type": "string"}, {"name": "createdBy", "type": "string"}]}], "default": null}, {"name": "whaleFish", "type": ["null", {"type": "record", "name": "Fish", "fields": [{"name": "name", "type": "string"}, {"name": "finsCount", "type": "long"}]}], "default": null}, {"name": "lionAnimal", "type": ["null", "Cat"], "default": null}]}
```
