### ISSUE TITLE
Conda Support

### ISSUE THREAD

**Issue by Petzep** [marcosschroh/dataclasses-avroschema#706]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when amazing packages like these are not in the conda-forge channel

**Describe the solution you'd like**
[Adding the package to conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs/).
The creation of a recipe is straight forward, as the python package is available in PyPi. This allows using `grayskull` to automatically generate a recipe.

Unfortunately, the package [inflector](https://pypi.org/project/Inflector/) is not available on conda-forge.
Usage of the inflector package can be substituted by the [inflection](https://anaconda.org/conda-forge/inflection) package.

**Additional context**
For the community, by the community. I can help with the changes needed

**Comment by marcosschroh** [comment]
@Petzep I will try to add the package to `conda` asap. Thanks for reporting the issue.

**Comment by marcosschroh** [comment]
@Petzep https://github.com/conda-forge/staged-recipes/pull/27276

Any ideas why some checks are failing? It seems that for other PRs for python packages the same checks are failing as well.

**Comment by Petzep** [comment]
According to the [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1002636&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=886) there is a conflict with the package python-datautil ([PyPi](https://pypi.org/project/python-dateutil), [conda-forge](https://anaconda.org/conda-forge/python-dateutil))

The latest version on Conda-forge is 2.9.0 and according to the [history at PyPi](https://pypi.org/project/python-dateutil/#history) the latest version is 2.9.0.post0.

So far so good, but the thing that confuses me is that recipe for the `dataclasses-avroschema` package specifies `python-dateutil >=2.9.0,<3.0.0` but the pipeline fails due to `dataclasses-avroschema 0.62.6 has requirement python-dateutil<3.0.0,>=2.9.0.post0, but you have python-dateutil 2.9.0`

I think it has to do with #645 as it set the requirement the dependency to `python-dateutil == 2.9.0.post0`
I requested an update of the feedstock https://github.com/conda-forge/python-dateutil-feedstock/issues/27

The bot of conda-forge already created a PR (https://github.com/conda-forge/python-dateutil-feedstock/pull/28)
Once that one is approved by the maintainers and the conda package is updated the issue could be fixed automagically.

If not, you could change the requirement in the recipe form `python-dateutil >=2.9.0,<3.0.0`  to `python-dateutil >=2.9.0.post0,<3.0.0` just to be sure.

I hope this will help 😁

**Comment by marcosschroh** [comment]
I think I will change the requirement `python-dateutil = "^2"`.

**Comment by marcosschroh** [comment]
Done. Let’s wait for the merge

**Comment by Petzep** [comment]
Nice, it works!

Congratulations! 🥳 
https://anaconda.org/conda-forge/dataclasses-avroschema
