### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by drawnwren** [marcosschroh/dataclasses-avroschema#739]
**Describe the bug**
While doing `AvroBaseModel.avro_schema_to_python()`, I get the following exception:
```
RuntimeError: Type not yet supported: <class 'dataclasses_avroschema.pydantic.main.AvroBaseModel'>
```

I don't have any idea which type this is or where it is in the code. It would be great if this error included some information about which type is not supported and potentially how I can fix the error.

**Comment by marcosschroh** [comment]
Can you share the Python class that you are trying to get the schema from?

**Comment by drawnwren** [comment]
So, it turned out that I think it was happening when the schema is the empty string. Might be nice to get an input validation error.

**Comment by marcosschroh** [comment]
Yeah, it makes sense. I wil fix it.
