### ISSUE TITLE
Allow statement to specify the casing (camel case, snake case, uppercase, etc) for field names when serializing/deserializing

### ISSUE THREAD

**Issue by tmilicic** [marcosschroh/dataclasses-avroschema#79]
**Feature Description**
When using Avro data format with different sources - some written in Scala, some in Python, it would be nice to have a converter between casing, so that one is not forced to use camel case in Python for example.

**Feature Example**
```
from dataclasses import dataclass

@dataclass
class Event(AvroModel):
    event_id: str

User.avro_schema(case='camel_case')

'{
    "type": "record",
    "name": "Event",
    "namespace": "Event.v1",
    "fields": [
        {"name": "eventId", "type": "string"}
    ]
}'

Event.serialize(case='camel_case')
Event.deserialize(case='snake_case')
```

**Comment by marcosschroh** [comment]
Hi @tmilicic ,

I will work in the feature request asap. Thanks

**Comment by tmilicic** [comment]
Thank you so much @marcosschroh!

**Comment by marcosschroh** [comment]
@tmilicic I have created a PR for this feature: https://github.com/marcosschroh/dataclasses-avroschema/pull/95 . You can test it if you want. It only works for schema generation. I will try to add the same functionality for data serialization

**Comment by tmilicic** [comment]
@marcosschroh thank you! I will look into it as soon as possible

**Comment by sachinruk** [comment]
Hello, has this been implemented where you can get camelcase for an instance as opposed to just the schema?
