### ISSUE TITLE
record types are duplicated in generated schema when referenced by more than one field

### ISSUE THREAD

**Issue by tomkrussel** [marcosschroh/dataclasses-avroschema#80]
**Describe the bug**
If a dataclass has fields whose types are other dataclasses the generated schema properly embeds a "record" object that describes the child field. However if the same child field type appears more than once in the dataclass the same "record" object is duplicated in the schema. The resulting schema cannot be parsed by apache's avro python library - failing with an error such as: avro.schema.SchemaParseException: The name "Location" is already in use. 

**To Reproduce**
The following simple set of dataclasses and the 3 lines of code after them will reproduce the error:

```
import avro
from dataclasses import dataclass
from dataclasses_avroschema import AvroModel
from datetime import datetime
import json


@dataclass
class Location(AvroModel):
    latitude: float
    longitude: float


@dataclass
class Trip(AvroModel):

    start_time: datetime
    start_location: Location
    finish_time: datetime
    finish_location: Location


trip_schema_dict = Trip.avro_schema_to_python()
print(json.dumps(trip_schema_dict, indent=2))
trip_schema = avro.schema.parse(json.dumps(trip_schema_dict))
```

**Expected behavior**
The generated schema should be valid and parseable by the apache avro library.

**Comment by marcosschroh** [comment]
Hi @tomkrussel 

Thanks for reporting the issue. I am working in a fix.

Besides this, I would recommend you to parse the schema with `fastavro` instead of `avro`. `dataclasses-avroschema` uses `fastavro` to validate the schemas.

**Comment by tomkrussel** [comment]
Thank you for addressing!  I appreciate the suggestion to use `fastavro`, however AFAIK that is a python only solution and one of the major focuses of the effort for which I am hoping to use this package is to provide AVRO schemas that can be used by producers and consumers written in any number of languages including python, C, C++, C# and Java.

The same apache project that produced the AVRO specification also provides libraries for each of these languages. If the python AVRO package from apache is incorrectly flagging the generated schema as invalid, then this issue should be pushed to that project. But if the generated schema is actually invalid (which I believe is the case), then it would be best to resolve the issue in this package.

Seems from your response that you're working on a fix so you agree. If that's not the case or if I can contribute in any way, please let me know.

**Comment by marcosschroh** [comment]
Hi,

Indeed, there is a bug in `dataclasses-avroschema` because of name collision. For nested schemas we are using the class name to generate the value `name`. In this case, the name `Location` is used twice, see the comments in the following `dict`, and the result is an invalid `avro schema`.

```python
{
  "type": "record",
  "name": "Trip",
  "fields": [
    {
      "name": "start_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "start_location",
      "type": {
        "type": "record",
        "name": "Location",  # first appearance
        "fields": [
          {
            "name": "latitude",
            "type": "float"
          },
          {
            "name": "longitude",
            "type": "float"
          }
        ],
        "doc": "Location(latitude: float, longitude: float)"
      }
    },
    {
      "name": "finish_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "finish_location",
      "type": {
        "type": "record",
        "name": "Location",  # second appearance, and the collision
        "fields": [
          {
            "name": "latitude",
            "type": "float"
          },
          {
            "name": "longitude",
            "type": "float"
          }
        ],
        "doc": "Location(latitude: float, longitude: float)"
      }
    }
  ],
  "doc": "Trip(start_time: datetime.datetime, start_location: __main__.Location, finish_time: datetime.datetime, finish_location: __main__.Location)"
}
```

For this cases, we need to generate the name in such a way to avoid collisions. I have this [PR](https://github.com/marcosschroh/dataclasses-avroschema/pull/81) that fixs this cases generating the nested names based on the `{field_name}_{class_nested_name}_`record`. With the {field_name} we can make sure that the name is unique. With the fix, the avro schema will look like:

```python
{
  "type": "record",
  "name": "Trip",
  "fields": [
    {
      "name": "start_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "start_location",
      "type": {
        "type": "record",
        "name": "start_location_record",  # first appearance
        "fields": [
          {
            "name": "latitude",
            "type": "float"
          },
          {
            "name": "longitude",
            "type": "float"
          }
        ],
        "doc": "Location(latitude: float, longitude: float)"
      }
    },
    {
      "name": "finish_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "finish_location",
      "type": {
        "type": "record",
        "name": "finish_location_record",  # second appearance, no collision
        "fields": [
          {
            "name": "latitude",
            "type": "float"
          },
          {
            "name": "longitude",
            "type": "float"
          }
        ],
        "doc": "Location(latitude: float, longitude: float)"
      }
    }
  ],
  "doc": "Trip(start_time: datetime.datetime, start_location: __main__.Location, finish_time: datetime.datetime, finish_location: __main__.Location)"
}
```

and it is a valid `avro` schema:

```python
avro.schema.parse(json.dumps(trip_schema_dict))

# >>> <avro.schema.RecordSchema at 0x10c0901d0>
```

Let me know what you think @tomkrussel

**Comment by tomkrussel** [comment]
That will work. Another solution that avoids duplication of the nested `record` is to refer back to the 1st occurrence by name. This however requires that the schemas has a namespace and (for apache's `avro` library anyway) requires that the namespace appear in the schema before the `record`s. The resulting schema is more compact, and would look like this:

```
{
  "namespace": "foo",
  "type": "record",
  "name": "Trip",
  "fields": [
    {
      "name": "start_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "start_location",
      "type": {
        "type": "record",
        "name": "Location",
        "fields": [
          {
            "name": "latitude",
            "type": "float"
          },
          {
            "name": "longitude",
            "type": "float"
          }
        ],
        "doc": "Location(latitude: float, longitude: float)"
      }
    },
    {
      "name": "finish_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "finish_location",
      "type": "foo.Location"
    }
  ],
  "doc": "Trip(start_time: datetime.datetime, start_location: __main__.Location, finish_time: datetime.datetime, finish_location: __main__.Location)"
}
```

Your solution is valid `avro` schema so it also works. I like the end result of the above solution better, but that may be considered a feature request since your solution does resolve the issue.

Thanks!

**Comment by marcosschroh** [comment]
Yes, I agree. Your proposal is more elegant and this is why namespaces exists. I will merge my solution and we can try to implement your solution in the future.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/81
