### ISSUE TITLE
Union field with default generating out-of-spec schema

### ISSUE THREAD

**Issue by xgamer4** [marcosschroh/dataclasses-avroschema#85]
According to the Avro specification, the default value of a union corresponds to the first listed type in the union. 

[ default: A default value for this field, used when reading instances that lack this field (optional). Permitted values depend on the field's schema type, according to the table below. Default values for union fields correspond to the first schema in the union. Default values for bytes and fixed fields are JSON strings, where Unicode code points 0-255 are mapped to unsigned 8-bit byte values 0-255. ](http://avro.apache.org/docs/current/spec.html#schema_complex).

I've got three examples of this being broken below:

**To Reproduce**
Using this class:
```
@dataclass
class User(AvroModel):
    "An User"
**Expected behavior**
A clear and concise description of what you expected to happen.
    name: str
    age: int
    school_grade: typing.Optional[int]
    school_name: typing.Optional[str] = None
    school_id: typing.Union[int, str] = ''
```

it generates the following schema:
```{
   "type": "record", 
   "name": "User",
   "fields": [
       {"name": "name", "type": "string"},
       {"name": "age", "type": "long"},
       {"name": "school_grade", "type": ["long", "null"]},
       {"name": "school_name", "type": ["string", "null"], "default": null},
       {"name": "school_id", "type": ["long", "string"], "default": ""}], 
   "doc": "An User"
}
```

1. `school_id` is typed as a union of int and str, and a default that's a str, but the generated schema has a union beginning with `long` and a default that's a string.

2. `school_name` is typed as an Optional[str] (a union [str, None] according to the docs) that defaults to None, but the generated schema has a union beginning with 'str' and a default null.

3. This one isn't actually a bug, but I do think it potentially violates expectations. If I type something as Optional I'd expect null to be a possible default (else why would it be optional in the first place?). `school_grade` is typed as an Optional[int], but the generated schema has `long` as the first value, meaning null can't be the default. 

A fix for the first two would be to verify that the provided default (if there is one) is in the union, and if so set that type as the first in the union on generation. Another option would be to verify and throw an exception if the type isn't the first listed in the union, which would be more informative, but less friendly and probably not worth it for something that's specific to the avro schema.

It would probably be worth changing the logic so `Optional[T]` generates the union `[null, T]` instead of `[T, null]` as well. It makes more intuitive sense that something that's optional allows null to be the default than for it to require something of the type to be the default and require null to be explicitly assigned. 

EDIT: 
So specifically, the generated schema should look like this (including making `Optional[T]` generate `[null, T]`). 
```{
   "type": "record", 
   "name": "User",
   "fields": [
       {"name": "name", "type": "string"},
       {"name": "age", "type": "long"},
       {"name": "school_grade", "type": ["null", "long"]},
       {"name": "school_name", "type": ["null", "string"], "default": null},
       {"name": "school_id", "type": ["string", "long"], "default": ""}], 
   "doc": "An User"
}
```

**Comment by marcosschroh** [comment]
Hi @xgamer4 , thanks. makes sense your proposal.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/87
