### ISSUE TITLE
AttributeError: '_SpecialForm' object has no attribute 'avro_schema_to_python'

### ISSUE THREAD

**Issue by aeldaly-tc** [marcosschroh/dataclasses-avroschema#88]
Given a class such as this:

```
@dataclass
class BaseSchema(AvroModel):
    message_metadata: Dict[str, Any]
```

**To Reproduce**
calling 
`schema = BaseSchema.avro_schema()` 
produces the error 
`AttributeError: '_SpecialForm' object has no attribute 'avro_schema_to_python'`

**Expected behavior**
It should return the schema

**Comment by marcosschroh** [comment]
Thanks @aeldaly-tc. `Any` is not a valid type in `avro`, you must use a proper type as the documentation describe. Anyway, we should show a more user friendly message for this case.

**Comment by leoscalco** [comment]
Just a contribution, fields with datetime.timestamp type also throws the following exception:

AttributeError: 'method_descriptor' object has no attribute 'avro_schema_to_python'

**Comment by marcosschroh** [comment]
Hi @leoscalco,

Do you mean that is not working for datetimes that are represented as `timestamp`? If that is the case, we do not have support for that. The logical types supported are: https://marcosschroh.github.io/dataclasses-avroschema/logical_types/

Maybe we can do something about it.

**Comment by leoscalco** [comment]
I realized this after commenting here.

I was using long type for timestamps, but I found in your document the right way to work with dates.

Now, any sink connector is recognizing my date. Anyway thank you for support.

**Comment by marcosschroh** [comment]
Hi, 

Perfect. I was thinking to add a new type to handle this option but maybe it not worth it at all. the user can make `datetime.fromtimestamp(a_timestamp)` and use the `datetime.datetime` type

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/94
