### ISSUE TITLE
Union types that contain a type that require an avrocschema.types specifier fail to generate schema

### ISSUE THREAD

**Issue by xgamer4** [marcosschroh/dataclasses-avroschema#92]
**Describe the bug**
A field with a Union type, where the Union contains a type that requires a dataclasses_avroschema.types default to provide additional metadata (Decimal, Enum, etc) fails to generate a schema. 

**To Reproduce**
```python
@dataclass
class TestEnum(AvroModel):
    OptionalEnum: typing.Optional[types.Enum] = types.Enum(['Mr', 'Mrs', 'Miss', 'Ms'])
    # DateEnum = typing.Union[datetime, types.Enum] = types.Enum(['Mr', 'Mrs', 'Miss', 'Ms'])
    # DecimalEnum = typing.Union[decimal.Decimal, types.Enum] = (types.Decimal(precision=2, scale=1), types.Enum(['Mr', 'Mrs', 'Miss', 'Ms']))

print(TestEnum.avro_schema())
```

Generates the following stacktrace
```
faust_1  | Traceback (most recent call last):
faust_1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
faust_1  |     return _run_code(code, main_globals, None,
faust_1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
faust_1  |     exec(code, run_globals)
faust_1  |   File "/app/proj/__main__.py", line 17, in <module>
faust_1  |     print(TestEnum.avro_schema())
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_generator.py", line 58, in avro_schema
faust_1  |     return json.dumps(cls.generate_schema(schema_type=AVRO).render())
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_generator.py", line 46, in generate_schema
faust_1  |     cls.schema_def = cls._generate_avro_schema()
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_generator.py", line 54, in _generate_avro_schema
faust_1  |     return schema_definition.AvroSchemaDefinition("record", cls.klass, metadata=cls.metadata)
faust_1  |   File "<string>", line 9, in __init__
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_definition.py", line 55, in __post_init__
faust_1  |     self.fields = self.parse_dataclasses_fields()
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_definition.py", line 60, in parse_dataclasses_fields
faust_1  |     return self.parse_fields()
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_definition.py", line 63, in parse_fields
faust_1  |     return [
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/schema_definition.py", line 64, in <listcomp>
faust_1  |     AvroField(
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/fields.py", line 820, in field_factory
faust_1  |     return container_klass(  # type: ignore
faust_1  |   File "<string>", line 10, in __init__
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/fields.py", line 355, in __post_init__
faust_1  |     self.unions = self.generate_unions_type()
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/fields.py", line 382, in generate_unions_type
faust_1  |     unions.append(default_field.get_avro_type())
faust_1  |   File "/usr/local/lib/python3.8/site-packages/dataclasses_avroschema/fields.py", line 449, in get_avro_type
faust_1  |     "symbols": self.default.symbols,
faust_1  | AttributeError: '_MISSING_TYPE' object has no attribute 'symbols'
```

**Expected behavior**
An AvroSchema something like:

```python
 {"type": "record", "name": "TestEnum", "fields": [{"name": "OptionalEnum", "type": ["null", {"type": "enum", "name": "OptionalEnum", "symbols": ["Mr", "Mrs", "Miss", "Ms"]}]}], "doc": "TestEnum(OptionalEnum: dataclasses_avroschema.types.Enum = ['Mr', 'Mrs', 'Miss', 'Ms'])"}
```

**Comment by marcosschroh** [comment]
Thanks @xgamer4 , I think it is time to refactor `types.Enum`. I will try to solve this asap

**Comment by xgamer4** [comment]
@marcosschroh If you're thinking in terms of a refactor, the commented-out properties in the test code will also fail in similar ways, with the last line being especially notable because I'm not even sure of a clean way to declare a union property with multiple types that need defined from dataclasses-avroschemas.types. The tuple I added was a just the first thing that came to mind. 

Though generally any property typed something like `p: typing.Union[Decimal, datetime, Enum]` seems like it'd be convoluted and unlikely to appear in a normal scenario, so maybe having that be defined strangely or just not-currently-supported is fine. 

If there's something you think I can help with feel free to let me know either here or in Slack. I just knew enough to identify the problem, but didn't know the codebase well enough to want to start digging away at how all the types defaults interacted with everything.

**Comment by marcosschroh** [comment]
When I designed the `Enum` type the idea was to have a simple way to use it, without declaring extra classes. The problem comes that the Enum always must have a default value to declare the enum props. The use case that you present must generate a valid avro schema, so clearly is a bug in the library. To fix it, the Enum class should change and the user will have to define an extra type:


```python
class MyEnum(Enum):
    MR = 'Mr'
    MRS = 'Mrs'
    MISS = 'Miss'
    MS = 'Ms
    
    class Meta:
        namespace: 'my-namespace'
        aliases: 'my-alias'
        docs: 'my docs'

# Use the union

@dataclass
class TestEnum(AvroModel):
    OptionalEnum: typing.Optional[types.Enum] = None
    SuperEnum: typing.Optional[types.Enum] = MyEnum.MR
    DateEnum = typing.Union[datetime, MyEnum] = MyEnum.MISS
```

This changes should be applicable for `Decimal` and `Fixed` types as well

**Comment by aaronkub** [comment]
Hey @marcosschroh ! I have a current use case for a nullable enum field. I'm a newbie to open source contributing, but I'd be willing to try and tackle this if you're open to it.

**Comment by marcosschroh** [comment]
Hi @aaronkub 

> I'm a newbie to open source contributing

No problem,  I am looking forward to see your PR.  Let's start with `Enum` and late we can create more PRs for `Decimal` and `Fixed` types.

**Comment by pawelrubin** [comment]
I've stumbled on the same problem, I need a nullable enum field in my schema, but it's currently not working.

@aaronkub what's the current status of tackling this bug?

**Comment by pawelrubin** [comment]
As a workaround I recommend an empty string for the default value, which could be handled the same way as the `null` case.
```python
@dataclass
class Schema(AvroModel):
    my_enum: types.Enum = types.Enum(["FOO", "BAR", ""], default="")

**Comment by aaronkub** [comment]
> I've stumbled on the same problem, I need a nullable enum field in my schema, but it's currently not working.
> 
> @aaronkub what's the current status of tackling this bug?

Apologies, I've been distracted by other work. I'm hoping to get to this soon. Feel free to make this change if you're able to!

**Comment by aaronkub** [comment]
On second thought, I will commit to getting a PR open this weekend. 🙂
